// @generated by st3-client-codegen from docs/st3/client-v0/schemas.
// Run `cargo run -p st3-client-codegen -- --check` to verify byte stability.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

pub const API_VERSION: &str = "st3.client.v0";
pub const ERROR_VERSION: &str = "st3.client.error.v0";
pub const TERMINAL_SUBPROTOCOL: &str = "st3.client.terminal.v0";

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Envelope<T> {
    pub api_version: String,
    pub request_id: String,
    pub snapshot: Snapshot,
    pub value: T,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Snapshot {
    pub id: String,
    pub host_id: String,
    pub store_index: u64,
    pub projection_version: String,
    pub created_at: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct ErrorEnvelope {
    pub api_version: String,
    pub error_version: String,
    pub request_id: String,
    pub code: ErrorCode,
    pub message: String,
    pub retryable: bool,
    #[serde(default)]
    pub retry_after_ms: Option<u64>,
    #[serde(default)]
    pub details: BTreeMap<String, Value>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum ErrorCode {
    NotFound,
    Forbidden,
    UnsupportedCapability,
    ValidationFailed,
    IdempotencyConflict,
    StaleFence,
    CursorGap,
    PageCursorExpired,
    RateLimited,
    Internal,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Capability {
    pub id: String,
    pub version: u32,
    pub state: CapabilityState,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum CapabilityState {
    Granted,
    Ungranted,
    Unavailable,
    Unsupported,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Limits {
    pub max_page_items: usize,
    pub max_event_items: usize,
    pub max_response_bytes: usize,
    pub max_wait_ms: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Capabilities {
    pub kind: String,
    pub session_actor: String,
    pub transport: TransportKind,
    pub capabilities: Vec<Capability>,
    pub limits: Limits,
    pub event_cursor: String,
    pub oldest_event_cursor: String,
    pub schemas: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum TransportKind {
    Unix,
    FabricLoopback,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct PageInfo {
    pub limit: usize,
    pub has_more: bool,
    #[serde(default)]
    pub next_cursor: Option<String>,
    #[serde(default)]
    pub cursor_expires_at: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Page {
    pub kind: String,
    pub collection: String,
    pub items: Vec<Resource>,
    pub page: PageInfo,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct ResourceHeader {
    pub id: String,
    pub revision: String,
    pub updated_at: String,
    #[serde(default)]
    pub operational: Option<Operational>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct Operational {
    pub layer: String,
    pub actionable: bool,
    #[serde(default)]
    pub reasons: Vec<String>,
    #[serde(default)]
    pub owner_generation: Option<String>,
    #[serde(default)]
    pub runtime_incarnation: Option<String>,
}

macro_rules! resource_model {
    ($name:ident) => {
        #[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
        pub struct $name {
            #[serde(flatten)]
            pub header: ResourceHeader,
            #[serde(flatten)]
            pub fields: BTreeMap<String, Value>,
        }
    };
}
resource_model!(Attention);
resource_model!(Message);
resource_model!(Launch);
resource_model!(LaunchVariant);
resource_model!(LaunchDecision);
resource_model!(LaunchApproval);
resource_model!(Mission);
resource_model!(Work);
resource_model!(Agent);
resource_model!(Runtime);
resource_model!(Operation);
resource_model!(History);
resource_model!(Session);

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum Resource {
    Attention(Attention),
    Message(Message),
    Launch(Launch),
    LaunchVariant(LaunchVariant),
    LaunchDecision(LaunchDecision),
    LaunchApproval(LaunchApproval),
    Mission(Mission),
    Work(Work),
    Agent(Agent),
    Runtime(Runtime),
    Operation(Operation),
    History(History),
    Session(Session),
}

impl Resource {
    pub fn header(&self) -> &ResourceHeader {
        match self {
            Self::Attention(v) => &v.header,
            Self::Message(v) => &v.header,
            Self::Launch(v) => &v.header,
            Self::LaunchVariant(v) => &v.header,
            Self::LaunchDecision(v) => &v.header,
            Self::LaunchApproval(v) => &v.header,
            Self::Mission(v) => &v.header,
            Self::Work(v) => &v.header,
            Self::Agent(v) => &v.header,
            Self::Runtime(v) => &v.header,
            Self::Operation(v) => &v.header,
            Self::History(v) => &v.header,
            Self::Session(v) => &v.header,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TimelinePage {
    pub kind: String,
    pub session_id: String,
    pub items: Vec<TimelineEntry>,
    pub page: PageInfo,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TimelineEntry {
    pub id: String,
    pub sequence: u64,
    pub revision: u32,
    pub timestamp: String,
    pub role: TimelineRole,
    #[serde(rename = "type")]
    pub entry_type: TimelineType,
    #[serde(rename = "final")]
    pub is_final: bool,
    pub body: Value,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TimelineRole {
    System,
    User,
    Assistant,
    Tool,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TimelineType {
    Message,
    Content,
    ToolCall,
    ToolResult,
    Status,
    Error,
    Usage,
    Redaction,
    Truncation,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct EventPage {
    pub kind: String,
    pub oldest_cursor: String,
    pub resume_cursor: String,
    pub items: Vec<ProjectionEvent>,
    pub has_more: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct ProjectionEvent {
    pub id: String,
    pub epoch: String,
    pub sequence: u64,
    pub previous_cursor: String,
    pub next_cursor: String,
    pub timestamp: String,
    #[serde(rename = "type")]
    pub event_type: EventType,
    pub resource_ids: Vec<String>,
    pub snapshot_id: String,
    pub body: Value,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum EventType {
    #[serde(rename = "upsert")]
    Upsert,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "timeline.delta")]
    TimelineDelta,
    #[serde(rename = "terminal.available")]
    TerminalAvailable,
    #[serde(rename = "capabilities.changed")]
    CapabilitiesChanged,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
pub struct Fence {
    pub snapshot_id: String,
    #[serde(default)]
    pub subject_revisions: BTreeMap<String, String>,
    #[serde(default)]
    pub mission_generation: Option<String>,
    #[serde(default)]
    pub step_definition: Option<String>,
    #[serde(default)]
    pub attempt: Option<u32>,
    #[serde(default)]
    pub readiness_epoch: Option<u64>,
    #[serde(default)]
    pub runtime_incarnation: Option<String>,
    #[serde(default)]
    pub terminal_sequence: Option<u64>,
    #[serde(default)]
    pub preview_token: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum ActionType {
    #[serde(rename = "attention.resolve")]
    AttentionResolve,
    #[serde(rename = "message.send")]
    MessageSend,
    #[serde(rename = "message.read")]
    MessageRead,
    #[serde(rename = "message.close")]
    MessageClose,
    #[serde(rename = "launch.create")]
    LaunchCreate,
    #[serde(rename = "launch.revise")]
    LaunchRevise,
    #[serde(rename = "launch.preview")]
    LaunchPreview,
    #[serde(rename = "launch.approve")]
    LaunchApprove,
    #[serde(rename = "launch.cancel")]
    LaunchCancel,
    #[serde(rename = "mission.start")]
    MissionStart,
    #[serde(rename = "mission.revise")]
    MissionRevise,
    #[serde(rename = "mission.approve-revision")]
    MissionApproveRevision,
    #[serde(rename = "mission.cancel")]
    MissionCancel,
    #[serde(rename = "work.claim")]
    WorkClaim,
    #[serde(rename = "work.renew")]
    WorkRenew,
    #[serde(rename = "work.progress")]
    WorkProgress,
    #[serde(rename = "work.complete")]
    WorkComplete,
    #[serde(rename = "work.fail")]
    WorkFail,
    #[serde(rename = "work.release")]
    WorkRelease,
    #[serde(rename = "work.publish-mission")]
    WorkPublishMission,
    #[serde(rename = "runtime.stop")]
    RuntimeStop,
    #[serde(rename = "runtime.restart")]
    RuntimeRestart,
    #[serde(rename = "runtime.reset")]
    RuntimeReset,
    #[serde(rename = "runtime.context-clear")]
    RuntimeContextClear,
    #[serde(rename = "runtime.signal")]
    RuntimeSignal,
    #[serde(rename = "terminal.input")]
    TerminalInput,
    #[serde(rename = "terminal.resize")]
    TerminalResize,
    #[serde(rename = "terminal.attach")]
    TerminalAttach,
    #[serde(rename = "terminal.detach")]
    TerminalDetach,
    #[serde(rename = "pairing.revoke")]
    PairingRevoke,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct ActionRequest {
    pub api_version: String,
    pub id: String,
    #[serde(rename = "type")]
    pub action_type: ActionType,
    pub idempotency_key: String,
    pub fence: Fence,
    pub parameters: Value,
}

impl ActionRequest {
    pub fn new<P: Serialize>(
        id: impl Into<String>,
        action_type: ActionType,
        idempotency_key: impl Into<String>,
        fence: Fence,
        parameters: &P,
    ) -> Result<Self, serde_json::Error> {
        Ok(Self {
            api_version: API_VERSION.into(),
            id: id.into(),
            action_type,
            idempotency_key: idempotency_key.into(),
            fence,
            parameters: serde_json::to_value(parameters)?,
        })
    }
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
pub struct TargetParameters {
    pub target_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct AttentionResolveParameters {
    pub attention_id: String,
    pub outcome: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct MessageSendParameters {
    pub to: String,
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub in_reply_to: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum LaunchTarget {
    NewMission {
        mission_id: String,
        workspace: String,
    },
    MissionRun {
        mission_run_id: String,
        generation_id: String,
    },
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct LaunchCreateParameters {
    pub title: String,
    pub request: String,
    pub target: LaunchTarget,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct LaunchReviseParameters {
    pub launch_id: String,
    pub feedback: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct LaunchVariantParameters {
    pub launch_id: String,
    pub variant_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct MissionStartParameters {
    pub mission_id: String,
    pub workspace: String,
    pub inputs: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct MissionReviseParameters {
    pub mission_run_id: String,
    pub launch_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct WorkPublishMissionParameters {
    pub target_id: String,
    pub name: String,
    pub mission: Value,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct RuntimeSignalParameters {
    pub target_id: String,
    pub signal: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalInputParameters {
    pub terminal_id: String,
    pub mode: TerminalInputMode,
    pub value: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum TerminalInputMode {
    Line,
    Raw,
    Key,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalResizeParameters {
    pub terminal_id: String,
    pub rows: u16,
    pub columns: u16,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct ActionResult {
    pub kind: String,
    pub action_id: String,
    pub operation_id: String,
    pub status: ActionStatus,
    pub affected_ids: Vec<String>,
    pub snapshot_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum ActionStatus {
    Accepted,
    Completed,
    Rejected,
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct PairingBegin {
    pub api_version: String,
    pub device_name: String,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct PairingChallenge {
    pub kind: String,
    pub pairing_id: String,
    pub code: String,
    pub expires_at: String,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct PairingComplete {
    pub api_version: String,
    pub code: String,
    pub device_public_key: String,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct PairedSession {
    pub kind: String,
    pub device_id: String,
    pub session_actor: String,
    pub credential: String,
    pub scopes: Vec<String>,
    pub expires_at: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalLine {
    pub row: usize,
    pub text: String,
    pub redacted: bool,
    pub truncated: bool,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalCursor {
    pub row: usize,
    pub column: usize,
    pub visible: bool,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalScreen {
    pub kind: String,
    pub terminal_id: String,
    pub runtime_incarnation: String,
    pub rows: usize,
    pub columns: usize,
    pub cursor: TerminalCursor,
    pub title: String,
    pub lines: Vec<TerminalLine>,
    pub next_sequence: u64,
    pub truncated: bool,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalFrame {
    pub id: String,
    pub terminal_id: String,
    pub runtime_incarnation: String,
    pub sequence: u64,
    #[serde(rename = "type")]
    pub frame_type: TerminalFrameType,
    pub timestamp: String,
    pub body: Value,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum TerminalFrameType {
    Output,
    Resize,
    Title,
    Bell,
    Exit,
    Resync,
    #[serde(other)]
    Unknown,
}
#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
pub struct TerminalFramePage {
    pub kind: String,
    pub terminal_id: String,
    pub runtime_incarnation: String,
    pub frames: Vec<TerminalFrame>,
    pub resume_sequence: u64,
}
