// @generated by st3-client-codegen from schemas plus templates; do not edit this output.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public actor St3Client {
    public let baseURL: URL
    private let session: URLSession
    private var credential: String?

    public init(fabricLoopbackURL: URL, credential: String? = nil, session: URLSession = .shared) {
        self.baseURL = fabricLoopbackURL
        self.credential = credential
        self.session = session
    }

    public func setCredential(_ credential: String?) { self.credential = credential }
    public func capabilities() async throws -> Envelope<Capabilities> { try await get("v1/client/capabilities") }
    private func list(_ collection: String, cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> {
        var query: [URLQueryItem] = []
        if let cursor { query.append(.init(name: "cursor", value: cursor)) }
        if let limit { query.append(.init(name: "limit", value: String(limit))) }
        if history { query.append(.init(name: "history", value: "true")) }
        return try await get("v1/client/\(collection)", query: query)
    }
    public func nowList(ownerRun: String, cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> {
        var query: [URLQueryItem] = [.init(name: "owner_run", value: ownerRun)]
        if let cursor { query.append(.init(name: "cursor", value: cursor)) }
        if let limit { query.append(.init(name: "limit", value: String(limit))) }
        if history { query.append(.init(name: "history", value: "true")) }
        return try await get("v1/client/now", query: query)
    }
    private func resource(_ collection: String, id: String) async throws -> Envelope<Resource> { let routedID = collection == "glasses" ? (id.split(separator: "/").last.map(String.init) ?? id) : (collection == "launches" ? id.replacingOccurrences(of: "launch/", with: "") : id); return try await get("v1/client/\(collection)/\(routedID)") }
    public func timeline(sessionID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<TimelinePage> {
        var query: [URLQueryItem] = []
        if let cursor { query.append(.init(name: "cursor", value: cursor)) }
        if let limit { query.append(.init(name: "limit", value: String(limit))) }
        return try await get("v1/client/sessions/\(Self.routedSessionID(sessionID))/timeline", query: query)
    }
    public func conversationChanges(sessionID: String, after: String? = nil, waitMS: UInt64 = 0) async throws -> Envelope<ConversationChanges> {
        var query: [URLQueryItem] = [.init(name: "wait_ms", value: String(waitMS))]
        if let after { query.append(.init(name: "after", value: after)) }
        return try await get("v1/client/conversations/\(Self.routedSessionID(sessionID))/changes", query: query)
    }
    public func conversationStream(sessionID: String, after: String? = nil) -> AsyncThrowingStream<Envelope<ConversationChanges>, Error> {
        var components = URLComponents(url: baseURL.appending(path: "v1/client/conversations/\(Self.routedSessionID(sessionID))/stream"), resolvingAgainstBaseURL: false)!
        components.scheme = components.scheme == "https" ? "wss" : "ws"
        if let after { components.queryItems = [.init(name: "after", value: after)] }
        var request = URLRequest(url: components.url!); request.setValue("st3.client.conversation.v0", forHTTPHeaderField: "Sec-WebSocket-Protocol"); if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        let task = session.webSocketTask(with: request)
        return AsyncThrowingStream { continuation in
            continuation.onTermination = { _ in task.cancel(with: .normalClosure, reason: nil) }
            task.resume()
            Task {
                let decoder = JSONDecoder()
                while true {
                    let message: URLSessionWebSocketTask.Message
                    do { message = try await task.receive() } catch { continuation.finish(throwing: task.closeCode == .normalClosure ? nil : error); return }
                    do {
                        let data = try Self.websocketData(from: message)
                        if let error = try? decoder.decode(ErrorEnvelope.self, from: data) { throw error }
                        continuation.yield(try decoder.decode(Envelope<ConversationChanges>.self, from: data))
                    } catch { continuation.finish(throwing: error); task.cancel(with: .normalClosure, reason: nil); return }
                }
            }
        }
    }
    public func events(after: String? = nil, limit: Int? = nil, waitMS: UInt64? = nil) async throws -> Envelope<EventPage> {
        var query: [URLQueryItem] = []
        if let after { query.append(.init(name: "after", value: after)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; if let waitMS { query.append(.init(name: "wait_ms", value: String(waitMS))) }
        return try await get("v1/client/events", query: query)
    }
    private func submit(_ action: ActionRequest) async throws -> Envelope<ActionResult> { try await post("v1/client/actions", action) }
    public func listGlasses(cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { try await list("glasses", cursor: cursor, limit: limit) }
    public func getGlass(id: String) async throws -> Envelope<Glass> { try await get("v1/client/glasses/\(Self.routedSessionID(id.split(separator: "/").last.map(String.init) ?? id))") }
    public func putGlass(id: String, body: GlassPut, idempotencyKey: String) async throws -> Envelope<Glass> { try await request("v1/client/glasses/\(Self.routedSessionID(id.split(separator: "/").last.map(String.init) ?? id))", query: [], method: "PUT", body: try JSONEncoder().encode(body), idempotencyKey: idempotencyKey) }
    public func deleteGlass(id: String, body: GlassDelete, idempotencyKey: String) async throws -> Envelope<Glass> { try await request("v1/client/glasses/\(Self.routedSessionID(id.split(separator: "/").last.map(String.init) ?? id))", query: [], method: "DELETE", body: try JSONEncoder().encode(body), idempotencyKey: idempotencyKey) }
    public func glassesStream(subscriptionID: String = "glasses") -> AsyncThrowingStream<GlassCollectionFrame, Error> {
        var components = URLComponents(url: baseURL.appending(path: "v1/client/collections/stream"), resolvingAgainstBaseURL: false)!
        components.scheme = components.scheme == "https" ? "wss" : "ws"
        var request = URLRequest(url: components.url!); request.setValue("st3.client.collections.v0", forHTTPHeaderField: "Sec-WebSocket-Protocol"); if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        let task = session.webSocketTask(with: request)
        return AsyncThrowingStream { continuation in
            continuation.onTermination = { _ in task.cancel(with: .normalClosure, reason: nil) }
            task.resume()
            Task {
                do {
                    let command = try JSONSerialization.data(withJSONObject: ["kind":"subscribe", "id":subscriptionID, "collection":"glasses", "limit":100])
                    try await task.send(.string(String(decoding: command, as: UTF8.self)))
                    while true {
                        let data = try Self.websocketData(from: try await task.receive())
                        let frame = try JSONDecoder().decode(GlassCollectionFrame.self, from: data)
                        if frame.kind == "error" { throw NSError(domain: "St3Client", code: 0, userInfo: [NSLocalizedDescriptionKey: frame.message ?? "Glass subscription failed"]) }
                        if frame.kind == "resync" { try await task.send(.string(String(decoding: command, as: UTF8.self))); continue }
                        continuation.yield(frame)
                    }
                } catch { continuation.finish(throwing: task.closeCode == .normalClosure ? nil : error); task.cancel(with: .normalClosure, reason: nil) }
            }
        }
    }
    public func arrangementsStream(person: String, subscriptionID: String = "arrangements", limit: Int = 100) -> AsyncThrowingStream<ArrangementCollectionFrame, Error> {
        var components = URLComponents(url: baseURL.appending(path: "v1/client/collections/stream"), resolvingAgainstBaseURL: false)!
        components.scheme = components.scheme == "https" ? "wss" : "ws"
        var request = URLRequest(url: components.url!); request.setValue("st3.client.collections.v0", forHTTPHeaderField: "Sec-WebSocket-Protocol"); if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        let task = session.webSocketTask(with: request)
        return AsyncThrowingStream { continuation in
            continuation.onTermination = { _ in task.cancel(with: .normalClosure, reason: nil) }
            task.resume()
            Task {
                do {
                    let command = try JSONSerialization.data(withJSONObject: ["kind":"subscribe", "id":subscriptionID, "collection":"arrangements", "person":person, "limit":limit])
                    try await task.send(.string(String(decoding: command, as: UTF8.self)))
                    while true {
                        let data = try Self.websocketData(from: try await task.receive())
                        let frame = try JSONDecoder().decode(ArrangementCollectionFrame.self, from: data)
                        if frame.kind == "error" { throw NSError(domain: "St3Client", code: 0, userInfo: [NSLocalizedDescriptionKey: frame.message ?? "Arrangement subscription failed"]) }
                        if frame.kind == "resync" { try await task.send(.string(String(decoding: command, as: UTF8.self))); continue }
                        continuation.yield(frame)
                    }
                } catch { continuation.finish(throwing: task.closeCode == .normalClosure ? nil : error); task.cancel(with: .normalClosure, reason: nil) }
            }
        }
    }
    /// Keep one image (PNG, JPEG, GIF or WebP, at most 10 MiB) on the member this client talks to. Name the answer's `blob` in a `message.send` attachment.
    public func uploadBlob(_ bytes: Data, mediaType: String) async throws -> Envelope<BlobUpload> { try await request("v1/client/blobs", query: [], method: "POST", body: bytes, contentType: mediaType) }
    /// Up to 512 KiB of an attachment from `offset`, base64 in `data`.
    public func blobChunk(sha256: String, message: String? = nil, offset: UInt64 = 0) async throws -> Envelope<BlobChunk> {
        var query: [URLQueryItem] = [.init(name: "offset", value: String(offset))]
        if let message { query.append(.init(name: "message", value: message)) }
        return try await get("v1/client/blobs/\(sha256)/chunk", query: query)
    }
    /// A whole attachment, read in chunks. Pass the message that carries it.
    public func blob(sha256: String, message: String? = nil) async throws -> Data {
        var whole = Data()
        while true {
            let chunk = try await blobChunk(sha256: sha256, message: message, offset: UInt64(whole.count)).value
            guard let bytes = Data(base64Encoded: chunk.data) else { throw URLError(.cannotParseResponse) }
            if bytes.isEmpty && UInt64(whole.count) < chunk.size { throw URLError(.cannotParseResponse) }
            whole.append(bytes)
            if UInt64(whole.count) >= chunk.size { return whole }
        }
    }
    public func hostRepositories(id: String) async throws -> Envelope<HostRepositories> { try await get("v1/client/hosts/\(id)/repositories") }
    public func setsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("sets", cursor: cursor, limit: limit, history: history) }
    public func setsGet(id: String) async throws -> Envelope<Resource> { try await resource("sets", id: id) }
    public func documentGet(name: String) async throws -> Envelope<DocumentContent> { try await get("v1/client/documents/content", query: [.init(name: "name", value: name)]) }
    public func subjectDefinition(subject: String, showEnvValues: Bool = false) async throws -> Envelope<SubjectDefinition> { try await get("v1/client/subject-definition", query: [.init(name: "subject", value: subject), .init(name: "show_env_values", value: showEnvValues ? "true" : "false")]) }
    public func usagePeriod(sinceMS: UInt64? = nil, untilMS: UInt64? = nil) async throws -> Envelope<UsagePeriod> { var query: [URLQueryItem] = []; if let sinceMS { query.append(.init(name: "since_ms", value: String(sinceMS))) }; if let untilMS { query.append(.init(name: "until_ms", value: String(untilMS))) }; return try await get("v1/client/usage", query: query) }
    public func nowList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("now", cursor: cursor, limit: limit, history: history) }
    public func machinesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("machines", cursor: cursor, limit: limit, history: history) }
    public func devicesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("devices", cursor: cursor, limit: limit, history: history) }
    public func attentionList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("attention", cursor: cursor, limit: limit, history: history) }
    public func attentionGet(id: String) async throws -> Envelope<Resource> { try await resource("attention", id: id) }
    public func messagesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("messages", cursor: cursor, limit: limit, history: history) }
    public func messagesGet(id: String) async throws -> Envelope<Resource> { try await resource("messages", id: id) }
    public func launchesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("launches", cursor: cursor, limit: limit, history: history) }
    public func launchesGet(id: String) async throws -> Envelope<Resource> { try await resource("launches", id: id) }
    public func launchVariantsList(launchID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { var query: [URLQueryItem] = []; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/launches/\(launchID.replacingOccurrences(of: "launch/", with: ""))/variants", query: query) }
    public func launchDecisionsList(launchID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { var query: [URLQueryItem] = []; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/launches/\(launchID.replacingOccurrences(of: "launch/", with: ""))/decisions", query: query) }
    public func launchApprovalsList(launchID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { var query: [URLQueryItem] = []; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/launches/\(launchID.replacingOccurrences(of: "launch/", with: ""))/approvals", query: query) }
    public func missionsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("missions", cursor: cursor, limit: limit, history: history) }
    public func missionsGet(id: String) async throws -> Envelope<Resource> { try await resource("missions", id: id) }
    public func workList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("work", cursor: cursor, limit: limit, history: history) }
    public func workGet(id: String) async throws -> Envelope<Resource> { try await resource("work", id: id) }
    public func resourcesList(filters: ResourcesFilter = .init(), cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcesPage> { var query: [URLQueryItem] = []; if let openedBy = filters.openedBy { query.append(.init(name: "opened_by", value: openedBy)) }; if let kind = filters.kind { query.append(.init(name: "kind", value: kind)) }; if let subjectPrefix = filters.subjectPrefix { query.append(.init(name: "subject_prefix", value: subjectPrefix)) }; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/resources", query: query) }
    public func agentsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("agents", cursor: cursor, limit: limit, history: history) }
    public func agentsGet(id: String) async throws -> Envelope<Resource> { try await resource("agents", id: id) }
    public func agentDeclarationGet(id: String, revision: String? = nil, showEnvValues: Bool = false) async throws -> Envelope<AgentDeclaration> { var query: [URLQueryItem] = [.init(name: "show_env_values", value: showEnvValues ? "true" : "false")]; if let revision { query.append(.init(name: "revision", value: revision)) }; return try await get("v1/client/agent-declarations/\(id)", query: query) }
    public func runtimesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("runtimes", cursor: cursor, limit: limit, history: history) }
    public func runtimesGet(id: String) async throws -> Envelope<Resource> { try await resource("runtimes", id: id) }
    public func observersList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("observers", cursor: cursor, limit: limit, history: history) }
    public func observersGet(id: String) async throws -> Envelope<Resource> { try await resource("observers", id: id) }
    public func subscriptionsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("subscriptions", cursor: cursor, limit: limit, history: history) }
    public func subscriptionsGet(id: String) async throws -> Envelope<Resource> { try await resource("subscriptions", id: id) }
    public func lanesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("lanes", cursor: cursor, limit: limit, history: history) }
    public func lanesGet(id: String) async throws -> Envelope<Resource> { try await resource("lanes", id: id) }
    public func terminalsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("terminals", cursor: cursor, limit: limit, history: history) }
    public func operationsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("operations", cursor: cursor, limit: limit, history: history) }
    public func operationsGet(id: String) async throws -> Envelope<Resource> { try await resource("operations", id: id) }
    public func historyList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("history", cursor: cursor, limit: limit, history: history) }
    public func historyGet(id: String) async throws -> Envelope<Resource> { try await resource("history", id: id) }
    public func sessionsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("sessions", cursor: cursor, limit: limit, history: history) }
    public func sessionsGet(id: String) async throws -> Envelope<Resource> { try await resource("sessions", id: id) }
    public func conversationSearch(text: String, agent: String? = nil, since: String? = nil, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ConversationSearch> { var query: [URLQueryItem] = [.init(name: "text", value: text)]; for (name, value) in [("agent", agent), ("since", since), ("cursor", cursor)] { if let value { query.append(.init(name: name, value: value)) } }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/conversations/search", query: query) }
    public func arrangementsList(person: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ArrangementPage> { var query: [URLQueryItem] = [.init(name: "person", value: person)]; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/arrangements", query: query) }
    public func arrangementsGet(personName: String, uuid: String) async throws -> Envelope<Arrangement> { try await get("v1/client/arrangements/\(Self.routedSessionID(personName))/\(Self.routedSessionID(uuid))") }
    public func glassesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("glasses", cursor: cursor, limit: limit, history: history) }
    public func glassesGet(id: String) async throws -> Envelope<Resource> { try await resource("glasses", id: id) }
    public func agentCreate(id: String, idempotencyKey: String, fence: Fence, parameters: AgentCreateParameters) async throws -> Envelope<ActionResult> { try await submit(try .agentCreate(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func agentQueueMove(id: String, idempotencyKey: String, fence: Fence, parameters: AgentQueueMoveParameters) async throws -> Envelope<ActionResult> { try await submit(try .agentQueueMove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func agentResume(id: String, idempotencyKey: String, fence: Fence, parameters: AgentResumeParameters) async throws -> Envelope<ActionResult> { try await submit(try .agentResume(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func agentStart(id: String, idempotencyKey: String, fence: Fence, parameters: AgentStartParameters) async throws -> Envelope<ActionResult> { try await submit(try .agentStart(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func agentStop(id: String, idempotencyKey: String, fence: Fence, parameters: AgentStopParameters) async throws -> Envelope<ActionResult> { try await submit(try .agentStop(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func agentSuspend(id: String, idempotencyKey: String, fence: Fence, parameters: AgentSuspendParameters) async throws -> Envelope<ActionResult> { try await submit(try .agentSuspend(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func arrangementEdit(id: String, idempotencyKey: String, fence: Fence, parameters: ArrangementEditParameters) async throws -> Envelope<ActionResult> { try await submit(try .arrangementEdit(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func attentionResolve(id: String, idempotencyKey: String, fence: Fence, parameters: AttentionResolveParameters) async throws -> Envelope<ActionResult> { try await submit(try .attentionResolve(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func laneApprove(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) async throws -> Envelope<ActionResult> { try await submit(try .laneApprove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func laneJoin(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) async throws -> Envelope<ActionResult> { try await submit(try .laneJoin(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func laneLeave(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) async throws -> Envelope<ActionResult> { try await submit(try .laneLeave(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func laneMark(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) async throws -> Envelope<ActionResult> { try await submit(try .laneMark(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func laneMove(id: String, idempotencyKey: String, fence: Fence, parameters: LaneChangeParameters) async throws -> Envelope<ActionResult> { try await submit(try .laneMove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchApprove(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchVariantParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchApprove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchCancel(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchCancel(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchCreate(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchCreateParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchCreate(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchPreview(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchVariantParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchPreview(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchRevise(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchReviseParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchRevise(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func messageClose(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .messageClose(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func messageRead(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .messageRead(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func messageSend(id: String, idempotencyKey: String, fence: Fence, parameters: MessageSendParameters) async throws -> Envelope<ActionResult> { try await submit(try .messageSend(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionApproveRevision(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionApproveRevision(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionCancel(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionCancel(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionCancelRevision(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionCancelRevision(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionRevise(id: String, idempotencyKey: String, fence: Fence, parameters: MissionReviseParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionRevise(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionStart(id: String, idempotencyKey: String, fence: Fence, parameters: MissionStartParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionStart(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func pairingRevoke(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .pairingRevoke(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func reviewApprove(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .reviewApprove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func reviewReject(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .reviewReject(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func reviewRequestChanges(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .reviewRequestChanges(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeContextClear(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeContextClear(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeReset(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeReset(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeRestart(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeRestart(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeSignal(id: String, idempotencyKey: String, fence: Fence, parameters: RuntimeSignalParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeSignal(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeStop(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeStop(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func sessionImport(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .sessionImport(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalAttach(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalAttach(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalCreate(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalCreateParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalCreate(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalDetach(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalDetach(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalEnd(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalEnd(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalInput(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalInputParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalInput(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalResize(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalResizeParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalResize(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workAsk(id: String, idempotencyKey: String, fence: Fence, parameters: PersonAskParameters) async throws -> Envelope<ActionResult> { try await submit(try .workAsk(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workCancelAsk(id: String, idempotencyKey: String, fence: Fence, parameters: PersonStepParameters) async throws -> Envelope<ActionResult> { try await submit(try .workCancelAsk(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workClaim(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workClaim(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workComplete(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workComplete(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workDone(id: String, idempotencyKey: String, fence: Fence, parameters: PersonStepParameters) async throws -> Envelope<ActionResult> { try await submit(try .workDone(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workFail(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workFail(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workProgress(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workProgress(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workPublishMission(id: String, idempotencyKey: String, fence: Fence, parameters: WorkPublishMissionParameters) async throws -> Envelope<ActionResult> { try await submit(try .workPublishMission(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workRelease(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workRelease(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workRenew(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workRenew(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workRetry(id: String, idempotencyKey: String, fence: Fence, parameters: WorkRetryParameters) async throws -> Envelope<ActionResult> { try await submit(try .workRetry(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func beginPairing(deviceName: String, personID: String) async throws -> Envelope<PairingChallenge> { try await post("v1/client/pairings", PairingBegin(apiVersion: st3ClientAPIVersion, deviceName: deviceName, personID: personID)) }
    public func completePairing(pairingID: String, code: String, devicePublicKey: String) async throws -> Envelope<PairedSession> { try await post("v1/client/pairings/\(pairingID.replacingOccurrences(of: "pairing/", with: ""))/complete", PairingComplete(apiVersion: st3ClientAPIVersion, code: code, devicePublicKey: devicePublicKey)) }
    public func terminalScreen(_ id: String) async throws -> Envelope<TerminalScreen> { try await get("v1/client/terminals/\(id.replacingOccurrences(of: "terminal/", with: ""))/screen") }
    public func agentQueue(_ id: String) async throws -> Envelope<AgentQueue> { try await get("v1/client/agent-queues/\(id)") }
    /// Open the terminal stream one `terminal.attach` capability allows. Each element is a whole
    /// screen that replaces every earlier one: the current screen first, then one per change. The
    /// sequence finishes when the server closes the stream, and throws the server's error when it
    /// ends the stream, such as `stale-fence` after the terminal's runtime incarnation changes.
    public func terminalStream(_ id: String, incarnation: String? = nil, streamCapability: String) -> AsyncThrowingStream<Envelope<TerminalScreen>, Error> {
        var components = URLComponents(url: baseURL.appending(path: "v1/client/terminals/\(id.replacingOccurrences(of: "terminal/", with: ""))/stream"), resolvingAgainstBaseURL: false)!
        components.scheme = components.scheme == "https" ? "wss" : "ws"
        if let incarnation { components.queryItems = [.init(name: "incarnation", value: incarnation)] }
        var request = URLRequest(url: components.url!); request.setValue("\(st3ClientTerminalSubprotocol), st3.cap.\(streamCapability)", forHTTPHeaderField: "Sec-WebSocket-Protocol"); if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        let task = session.webSocketTask(with: request)
        return AsyncThrowingStream { continuation in
            continuation.onTermination = { _ in task.cancel(with: .normalClosure, reason: nil) }
            task.resume()
            Task {
                let decoder = JSONDecoder()
                while true {
                    let message: URLSessionWebSocketTask.Message
                    do { message = try await task.receive() } catch { continuation.finish(throwing: task.closeCode == .normalClosure ? nil : error); return }
                    do {
                        let data = try Self.websocketData(from: message)
                        if let error = try? decoder.decode(ErrorEnvelope.self, from: data) { throw error }
                        continuation.yield(try decoder.decode(Envelope<TerminalScreen>.self, from: data))
                    } catch { continuation.finish(throwing: error); task.cancel(with: .normalClosure, reason: nil); return }
                }
            }
        }
    }

    private static func websocketData(from message: URLSessionWebSocketTask.Message) throws -> Data {
        switch message { case .data(let data): return data; case .string(let text): return Data(text.utf8); @unknown default: throw URLError(.cannotParseResponse) }
    }

    private func get<T: Decodable & Sendable>(_ path: String, query: [URLQueryItem] = []) async throws -> T { try await request(path, query: query, method: "GET", body: Optional<Data>.none) }
    private func post<T: Decodable & Sendable, Body: Encodable>(_ path: String, _ body: Body) async throws -> T { try await request(path, query: [], method: "POST", body: try JSONEncoder().encode(body)) }
    private func request<T: Decodable & Sendable>(_ path: String, query: [URLQueryItem], method: String, body: Data?, idempotencyKey: String? = nil, contentType: String = "application/json") async throws -> T {
        var components = URLComponents(url: baseURL, resolvingAgainstBaseURL: false)!; let basePath = components.percentEncodedPath.trimmingCharacters(in: CharacterSet(charactersIn: "/")); components.percentEncodedPath = "/" + ([basePath, path].filter { !$0.isEmpty }.joined(separator: "/")); if !query.isEmpty { components.queryItems = query }
        // Query parameters are decoded as form data by the server, where an unescaped "+" is a space.
        components.percentEncodedQuery = components.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")
        var request = URLRequest(url: components.url!); request.httpMethod = method; request.httpBody = body; request.setValue("application/json", forHTTPHeaderField: "Accept")
        if body != nil { request.setValue(contentType, forHTTPHeaderField: "Content-Type") }; if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        if let idempotencyKey { request.setValue(idempotencyKey, forHTTPHeaderField: "Idempotency-Key") }
        let (data, response) = try await session.data(for: request); let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        if !(200..<300).contains(status) { throw try JSONDecoder().decode(ErrorEnvelope.self, from: data) }
        return try JSONDecoder().decode(T.self, from: data)
    }

    static func routedSessionID(_ value: String) -> String {
        let innerID = value.hasPrefix("session/") ? String(value.dropFirst("session/".count)) : value
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_.~"))
        return innerID.addingPercentEncoding(withAllowedCharacters: allowed) ?? ""
    }
}
