// @generated by st3-client-codegen from schemas plus templates; do not edit this output.
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public actor St3Client {
    public let baseURL: URL
    private let session: URLSession
    private var credential: String?

    public init(fabricLoopbackURL: URL, credential: String? = nil, session: URLSession = .shared) {
        self.baseURL = fabricLoopbackURL
        self.credential = credential
        self.session = session
    }

    public func setCredential(_ credential: String?) { self.credential = credential }
    public func capabilities() async throws -> Envelope<Capabilities> { try await get("v1/client/capabilities") }
    private func list(_ collection: String, cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> {
        var query: [URLQueryItem] = []
        if let cursor { query.append(.init(name: "cursor", value: cursor)) }
        if let limit { query.append(.init(name: "limit", value: String(limit))) }
        if history { query.append(.init(name: "history", value: "true")) }
        return try await get("v1/client/\(collection)", query: query)
    }
    public func nowList(ownerRun: String, cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> {
        var query: [URLQueryItem] = [.init(name: "owner_run", value: ownerRun)]
        if let cursor { query.append(.init(name: "cursor", value: cursor)) }
        if let limit { query.append(.init(name: "limit", value: String(limit))) }
        if history { query.append(.init(name: "history", value: "true")) }
        return try await get("v1/client/now", query: query)
    }
    private func resource(_ collection: String, id: String) async throws -> Envelope<Resource> { let routedID = collection == "launches" ? id.replacingOccurrences(of: "launch/", with: "") : id; return try await get("v1/client/\(collection)/\(routedID)") }
    public func timeline(sessionID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<TimelinePage> {
        var query: [URLQueryItem] = []
        if let cursor { query.append(.init(name: "cursor", value: cursor)) }
        if let limit { query.append(.init(name: "limit", value: String(limit))) }
        return try await get("v1/client/sessions/\(Self.routedSessionID(sessionID))/timeline", query: query)
    }
    public func events(after: String? = nil, limit: Int? = nil, waitMS: UInt64? = nil) async throws -> Envelope<EventPage> {
        var query: [URLQueryItem] = []
        if let after { query.append(.init(name: "after", value: after)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; if let waitMS { query.append(.init(name: "wait_ms", value: String(waitMS))) }
        return try await get("v1/client/events", query: query)
    }
    private func submit(_ action: ActionRequest) async throws -> Envelope<ActionResult> { try await post("v1/client/actions", action) }
    public func nowList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("now", cursor: cursor, limit: limit, history: history) }
    public func machinesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("machines", cursor: cursor, limit: limit, history: history) }
    public func devicesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("devices", cursor: cursor, limit: limit, history: history) }
    public func attentionList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("attention", cursor: cursor, limit: limit, history: history) }
    public func attentionGet(id: String) async throws -> Envelope<Resource> { try await resource("attention", id: id) }
    public func messagesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("messages", cursor: cursor, limit: limit, history: history) }
    public func messagesGet(id: String) async throws -> Envelope<Resource> { try await resource("messages", id: id) }
    public func launchesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("launches", cursor: cursor, limit: limit, history: history) }
    public func launchesGet(id: String) async throws -> Envelope<Resource> { try await resource("launches", id: id) }
    public func launchVariantsList(launchID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { var query: [URLQueryItem] = []; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/launches/\(launchID.replacingOccurrences(of: "launch/", with: ""))/variants", query: query) }
    public func launchDecisionsList(launchID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { var query: [URLQueryItem] = []; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/launches/\(launchID.replacingOccurrences(of: "launch/", with: ""))/decisions", query: query) }
    public func launchApprovalsList(launchID: String, cursor: String? = nil, limit: Int? = nil) async throws -> Envelope<ResourcePage> { var query: [URLQueryItem] = []; if let cursor { query.append(.init(name: "cursor", value: cursor)) }; if let limit { query.append(.init(name: "limit", value: String(limit))) }; return try await get("v1/client/launches/\(launchID.replacingOccurrences(of: "launch/", with: ""))/approvals", query: query) }
    public func missionsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("missions", cursor: cursor, limit: limit, history: history) }
    public func missionsGet(id: String) async throws -> Envelope<Resource> { try await resource("missions", id: id) }
    public func workList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("work", cursor: cursor, limit: limit, history: history) }
    public func workGet(id: String) async throws -> Envelope<Resource> { try await resource("work", id: id) }
    public func agentsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("agents", cursor: cursor, limit: limit, history: history) }
    public func agentsGet(id: String) async throws -> Envelope<Resource> { try await resource("agents", id: id) }
    public func runtimesList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("runtimes", cursor: cursor, limit: limit, history: history) }
    public func runtimesGet(id: String) async throws -> Envelope<Resource> { try await resource("runtimes", id: id) }
    public func terminalsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("terminals", cursor: cursor, limit: limit, history: history) }
    public func operationsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("operations", cursor: cursor, limit: limit, history: history) }
    public func operationsGet(id: String) async throws -> Envelope<Resource> { try await resource("operations", id: id) }
    public func historyList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("history", cursor: cursor, limit: limit, history: history) }
    public func historyGet(id: String) async throws -> Envelope<Resource> { try await resource("history", id: id) }
    public func sessionsList(cursor: String? = nil, limit: Int? = nil, history: Bool = false) async throws -> Envelope<ResourcePage> { try await list("sessions", cursor: cursor, limit: limit, history: history) }
    public func sessionsGet(id: String) async throws -> Envelope<Resource> { try await resource("sessions", id: id) }
    public func attentionResolve(id: String, idempotencyKey: String, fence: Fence, parameters: AttentionResolveParameters) async throws -> Envelope<ActionResult> { try await submit(try .attentionResolve(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchApprove(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchVariantParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchApprove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchCancel(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchCancel(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchCreate(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchCreateParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchCreate(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchPreview(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchVariantParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchPreview(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func launchRevise(id: String, idempotencyKey: String, fence: Fence, parameters: LaunchReviseParameters) async throws -> Envelope<ActionResult> { try await submit(try .launchRevise(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func messageClose(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .messageClose(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func messageRead(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .messageRead(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func messageSend(id: String, idempotencyKey: String, fence: Fence, parameters: MessageSendParameters) async throws -> Envelope<ActionResult> { try await submit(try .messageSend(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionApproveRevision(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionApproveRevision(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionCancel(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionCancel(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionCancelRevision(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionCancelRevision(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionRevise(id: String, idempotencyKey: String, fence: Fence, parameters: MissionReviseParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionRevise(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func missionStart(id: String, idempotencyKey: String, fence: Fence, parameters: MissionStartParameters) async throws -> Envelope<ActionResult> { try await submit(try .missionStart(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func pairingRevoke(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .pairingRevoke(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func reviewApprove(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .reviewApprove(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func reviewReject(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .reviewReject(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeContextClear(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeContextClear(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeReset(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeReset(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeRestart(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeRestart(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeSignal(id: String, idempotencyKey: String, fence: Fence, parameters: RuntimeSignalParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeSignal(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func runtimeStop(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .runtimeStop(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func sessionImport(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .sessionImport(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalAttach(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalAttach(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalDetach(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalDetach(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalInput(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalInputParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalInput(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func terminalResize(id: String, idempotencyKey: String, fence: Fence, parameters: TerminalResizeParameters) async throws -> Envelope<ActionResult> { try await submit(try .terminalResize(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workClaim(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workClaim(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workComplete(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workComplete(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workFail(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workFail(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workProgress(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workProgress(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workPublishMission(id: String, idempotencyKey: String, fence: Fence, parameters: WorkPublishMissionParameters) async throws -> Envelope<ActionResult> { try await submit(try .workPublishMission(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workRelease(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workRelease(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func workRenew(id: String, idempotencyKey: String, fence: Fence, parameters: TargetParameters) async throws -> Envelope<ActionResult> { try await submit(try .workRenew(id: id, idempotencyKey: idempotencyKey, fence: fence, parameters: parameters)) }
    public func beginPairing(deviceName: String, personID: String) async throws -> Envelope<PairingChallenge> { try await post("v1/client/pairings", PairingBegin(apiVersion: st3ClientAPIVersion, deviceName: deviceName, personID: personID)) }
    public func completePairing(pairingID: String, code: String, devicePublicKey: String) async throws -> Envelope<PairedSession> { try await post("v1/client/pairings/\(pairingID.replacingOccurrences(of: "pairing/", with: ""))/complete", PairingComplete(apiVersion: st3ClientAPIVersion, code: code, devicePublicKey: devicePublicKey)) }
    public func terminalScreen(_ id: String) async throws -> Envelope<TerminalScreen> { try await get("v1/client/terminals/\(id.replacingOccurrences(of: "terminal/", with: ""))/screen") }
    public func terminalFrames(_ id: String, after: UInt64? = nil, incarnation: String? = nil, streamCapability: String) async throws -> TerminalStreamBatch {
        var components = URLComponents(url: baseURL.appending(path: "v1/client/terminals/\(id.replacingOccurrences(of: "terminal/", with: ""))/stream"), resolvingAgainstBaseURL: false)!
        components.scheme = components.scheme == "https" ? "wss" : "ws"
        var query: [URLQueryItem] = []; if let after { query.append(.init(name: "after", value: String(after))) }; if let incarnation { query.append(.init(name: "incarnation", value: incarnation)) }; if !query.isEmpty { components.queryItems = query }
        var request = URLRequest(url: components.url!); request.setValue("\(st3ClientTerminalSubprotocol), st3.cap.\(streamCapability)", forHTTPHeaderField: "Sec-WebSocket-Protocol"); if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        let task = session.webSocketTask(with: request); task.resume(); defer { task.cancel(with: .normalClosure, reason: nil) }
        let decoder = JSONDecoder()
        let screenData = try websocketData(from: try await task.receive())
        if let error = try? decoder.decode(ErrorEnvelope.self, from: screenData) { throw error }
        let screen = try decoder.decode(Envelope<TerminalScreen>.self, from: screenData)
        let frames: Envelope<TerminalFramePage>?
        do {
            let data = try websocketData(from: try await task.receive())
            if let error = try? decoder.decode(ErrorEnvelope.self, from: data) { throw error }
            frames = try decoder.decode(Envelope<TerminalFramePage>.self, from: data)
        } catch let error as ErrorEnvelope { throw error } catch { frames = nil }
        return TerminalStreamBatch(screen: screen, frames: frames)
    }

    private func websocketData(from message: URLSessionWebSocketTask.Message) throws -> Data {
        switch message { case .data(let data): return data; case .string(let text): return Data(text.utf8); @unknown default: throw URLError(.cannotParseResponse) }
    }

    private func get<T: Decodable & Sendable>(_ path: String, query: [URLQueryItem] = []) async throws -> T { try await request(path, query: query, method: "GET", body: Optional<Data>.none) }
    private func post<T: Decodable & Sendable, Body: Encodable>(_ path: String, _ body: Body) async throws -> T { try await request(path, query: [], method: "POST", body: try JSONEncoder().encode(body)) }
    private func request<T: Decodable & Sendable>(_ path: String, query: [URLQueryItem], method: String, body: Data?) async throws -> T {
        var components = URLComponents(url: baseURL, resolvingAgainstBaseURL: false)!; let basePath = components.percentEncodedPath.trimmingCharacters(in: CharacterSet(charactersIn: "/")); components.percentEncodedPath = "/" + ([basePath, path].filter { !$0.isEmpty }.joined(separator: "/")); if !query.isEmpty { components.queryItems = query }
        var request = URLRequest(url: components.url!); request.httpMethod = method; request.httpBody = body; request.setValue("application/json", forHTTPHeaderField: "Accept")
        if body != nil { request.setValue("application/json", forHTTPHeaderField: "Content-Type") }; if let credential { request.setValue("Bearer \(credential)", forHTTPHeaderField: "Authorization") }
        let (data, response) = try await session.data(for: request); let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        if !(200..<300).contains(status) { throw try JSONDecoder().decode(ErrorEnvelope.self, from: data) }
        return try JSONDecoder().decode(T.self, from: data)
    }

    static func routedSessionID(_ value: String) -> String {
        let innerID = value.hasPrefix("session/") ? String(value.dropFirst("session/".count)) : value
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_.~"))
        return innerID.addingPercentEncoding(withAllowedCharacters: allowed) ?? ""
    }
}
