// @generated by st3-client-codegen; contract sha256 497613e84955367abe65ed7c855078d170e60a91312eafcb9d5143a2517d0515

import Foundation

public let st3ClientContractSHA256 = "497613e84955367abe65ed7c855078d170e60a91312eafcb9d5143a2517d0515"

public enum ActionType: String, Codable, CaseIterable, Sendable {
    case attentionResolve = "attention.resolve"
    case launchApprove = "launch.approve"
    case launchCancel = "launch.cancel"
    case launchCreate = "launch.create"
    case launchPreview = "launch.preview"
    case launchRevise = "launch.revise"
    case messageClose = "message.close"
    case messageRead = "message.read"
    case messageSend = "message.send"
    case missionApproveRevision = "mission.approve-revision"
    case missionCancel = "mission.cancel"
    case missionCancelRevision = "mission.cancel-revision"
    case missionRevise = "mission.revise"
    case missionStart = "mission.start"
    case pairingRevoke = "pairing.revoke"
    case reviewApprove = "review.approve"
    case reviewReject = "review.reject"
    case runtimeContextClear = "runtime.context-clear"
    case runtimeReset = "runtime.reset"
    case runtimeRestart = "runtime.restart"
    case runtimeSignal = "runtime.signal"
    case runtimeStop = "runtime.stop"
    case sessionImport = "session.import"
    case terminalAttach = "terminal.attach"
    case terminalDetach = "terminal.detach"
    case terminalInput = "terminal.input"
    case terminalResize = "terminal.resize"
    case workClaim = "work.claim"
    case workComplete = "work.complete"
    case workFail = "work.fail"
    case workProgress = "work.progress"
    case workPublishMission = "work.publish-mission"
    case workRelease = "work.release"
    case workRenew = "work.renew"
}

public enum ReadOperation: String, CaseIterable, Sendable {
    case capabilitiesGet = "capabilities.get"
    case nowList = "now.list"
    case machinesList = "machines.list"
    case devicesList = "devices.list"
    case attentionList = "attention.list"
    case attentionGet = "attention.get"
    case messagesList = "messages.list"
    case messagesGet = "messages.get"
    case launchesList = "launches.list"
    case launchesGet = "launches.get"
    case launchVariantsList = "launch-variants.list"
    case launchDecisionsList = "launch-decisions.list"
    case launchApprovalsList = "launch-approvals.list"
    case missionsList = "missions.list"
    case missionsGet = "missions.get"
    case workList = "work.list"
    case workGet = "work.get"
    case agentsList = "agents.list"
    case agentsGet = "agents.get"
    case runtimesList = "runtimes.list"
    case runtimesGet = "runtimes.get"
    case terminalsList = "terminals.list"
    case operationsList = "operations.list"
    case operationsGet = "operations.get"
    case historyList = "history.list"
    case historyGet = "history.get"
    case sessionsList = "sessions.list"
    case sessionsGet = "sessions.get"
    case timelineList = "timeline.list"
    case eventsList = "events.list"
    case terminalScreen = "terminal.screen"
}

public let st3ClientReadPaths: [ReadOperation: String] = [
    .capabilitiesGet: "/v1/client/capabilities",
    .nowList: "/v1/client/now",
    .machinesList: "/v1/client/machines",
    .devicesList: "/v1/client/devices",
    .attentionList: "/v1/client/attention",
    .attentionGet: "/v1/client/attention/{id}",
    .messagesList: "/v1/client/messages",
    .messagesGet: "/v1/client/messages/{id}",
    .launchesList: "/v1/client/launches",
    .launchesGet: "/v1/client/launches/{id}",
    .launchVariantsList: "/v1/client/launches/{id}/variants",
    .launchDecisionsList: "/v1/client/launches/{id}/decisions",
    .launchApprovalsList: "/v1/client/launches/{id}/approvals",
    .missionsList: "/v1/client/missions",
    .missionsGet: "/v1/client/missions/{id}",
    .workList: "/v1/client/work",
    .workGet: "/v1/client/work/{id}",
    .agentsList: "/v1/client/agents",
    .agentsGet: "/v1/client/agents/{id}",
    .runtimesList: "/v1/client/runtimes",
    .runtimesGet: "/v1/client/runtimes/{id}",
    .terminalsList: "/v1/client/terminals",
    .operationsList: "/v1/client/operations",
    .operationsGet: "/v1/client/operations/{id}",
    .historyList: "/v1/client/history",
    .historyGet: "/v1/client/history/{id}",
    .sessionsList: "/v1/client/sessions",
    .sessionsGet: "/v1/client/sessions/{id}",
    .timelineList: "/v1/client/sessions/{id}/timeline",
    .eventsList: "/v1/client/events",
    .terminalScreen: "/v1/client/terminals/{id}/screen",
]
