use anyhow::{Context as _, Result, bail};
use serde_json::Value;
use sha2::{Digest as _, Sha256};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() -> Result<()> {
    let check = std::env::args()
        .skip(1)
        .any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let operations_path = root.join("docs/st3/client-v0/schemas/operations.json");
    let schema_path = root.join("docs/st3/client-v0/schemas/client-v0.schema.json");
    let operations_bytes = std::fs::read(&operations_path).context("read operations manifest")?;
    let schema_bytes = std::fs::read(&schema_path).context("read client schema")?;
    let operations: Value = serde_json::from_slice(&operations_bytes)?;
    let actions = operations["actions"]
        .as_object()
        .context("actions object")?;
    let reads = operations["reads"].as_array().context("reads array")?;
    let digest = hex_digest(&[&schema_bytes, &operations_bytes]);
    let rust = rust_contract(&digest, actions.keys().map(String::as_str), reads)?;
    let swift = swift_contract(&digest, actions.keys().map(String::as_str), reads)?;
    output(
        &root.join("crates/st3-client/src/contract.rs"),
        &rust,
        check,
    )?;
    output(
        &root.join("clients/swift/St3Client/Sources/St3Client/Contract.generated.swift"),
        &swift,
        check,
    )?;
    Ok(())
}

fn output(path: &Path, contents: &str, check: bool) -> Result<()> {
    if check {
        let current =
            std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
        if current != contents {
            bail!(
                "{} is stale; run `cargo run -p st3-client-codegen`",
                path.display()
            );
        }
    } else {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
    }
    Ok(())
}

fn hex_digest(parts: &[&[u8]]) -> String {
    let mut hash = Sha256::new();
    for part in parts {
        hash.update(part);
    }
    let digest = hash.finalize();
    format!("{digest:x}")
}

fn pascal(value: &str) -> String {
    value
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_ascii_uppercase().to_string() + chars.as_str())
                .unwrap_or_default()
        })
        .collect()
}

fn rust_contract<'a>(
    digest: &str,
    actions: impl Iterator<Item = &'a str>,
    reads: &[Value],
) -> Result<String> {
    let actions = actions.collect::<Vec<_>>();
    let mut out = format!("// @generated by st3-client-codegen; contract sha256 {digest}\n\n");
    writeln!(
        out,
        "#[rustfmt::skip]\npub const CONTRACT_SHA256: &str = \"{digest}\";"
    )?;
    writeln!(
        out,
        "#[rustfmt::skip]\npub const ACTION_NAMES: &[&str] = &["
    )?;
    for action in &actions {
        writeln!(out, "    \"{action}\",")?;
    }
    writeln!(
        out,
        "];\n#[rustfmt::skip]\npub const READ_OPERATIONS: &[(&str, &str)] = &["
    )?;
    for read in reads {
        writeln!(
            out,
            "    (\"{}\", \"{}\"),",
            read["id"].as_str().context("read id")?,
            read["path"].as_str().context("read path")?
        )?;
    }
    writeln!(out, "];")?;
    Ok(out)
}

fn swift_contract<'a>(
    digest: &str,
    actions: impl Iterator<Item = &'a str>,
    reads: &[Value],
) -> Result<String> {
    let actions = actions.collect::<Vec<_>>();
    let mut out = format!(
        "// @generated by st3-client-codegen; contract sha256 {digest}\n\nimport Foundation\n\n"
    );
    writeln!(out, "public let st3ClientContractSHA256 = \"{digest}\"\n")?;
    writeln!(
        out,
        "public enum ActionType: String, Codable, CaseIterable, Sendable {{"
    )?;
    for action in &actions {
        writeln!(
            out,
            "    case {} = \"{}\"",
            lower_camel(&pascal(action)),
            action
        )?;
    }
    writeln!(
        out,
        "}}\n\npublic enum ReadOperation: String, CaseIterable, Sendable {{"
    )?;
    for read in reads {
        let id = read["id"].as_str().context("read id")?;
        writeln!(out, "    case {} = \"{}\"", lower_camel(&pascal(id)), id)?;
    }
    writeln!(
        out,
        "}}\n\npublic let st3ClientReadPaths: [ReadOperation: String] = ["
    )?;
    for read in reads {
        let id = read["id"].as_str().unwrap();
        writeln!(
            out,
            "    .{}: \"{}\",",
            lower_camel(&pascal(id)),
            read["path"].as_str().unwrap()
        )?;
    }
    writeln!(out, "]\n")?;
    Ok(out)
}

fn lower_camel(value: &str) -> String {
    let mut chars = value.chars();
    chars
        .next()
        .map(|first| first.to_ascii_lowercase().to_string() + chars.as_str())
        .unwrap_or_default()
}
