// @generated by st3-client-codegen; edit the template, then regenerate.
import { API_VERSION } from './Models.generated';
import type {
    ActionOf, ActionRequest, ActionResult, Capabilities, EnvelopeOf,
    ErrorEnvelope, EventPage, Page, PairingBegin, PairingChallenge,
    PairingComplete, PairedSession, Resource, TerminalScreen, TimelinePage,
} from './Models.generated';

export type PageOptions = { cursor?: string; limit?: number };
export type ListOptions = PageOptions & { history?: boolean; owner_run?: string; actor?: string; status?: string; native_only?: boolean };
export type EventOptions = { after?: string; limit?: number; wait_ms?: number };
export type ClientOptions = {
    baseUrl: string;
    credential?: () => string | undefined | Promise<string | undefined>;
    fetchImpl?: typeof fetch;
};

export class ClientError extends Error {
    constructor(public readonly response: ErrorEnvelope, public readonly status: number) {
        super(response.message);
        this.name = 'ClientError';
    }
}

function routedId(id: string): string {
    return id.replace(/^(launch|session|pairing)\//, '');
}

function query(options: Record<string, string | number | boolean | undefined>): string {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(options)) {
        if (value !== undefined) params.set(key, String(value));
    }
    const result = params.toString();
    return result ? `?${result}` : '';
}

function bounded(value: number | undefined, maximum: number, name: string): void {
    if (value !== undefined && (!Number.isSafeInteger(value) || value < 1 || value > maximum)) {
        throw new RangeError(`${name} must be an integer between 1 and ${maximum}`);
    }
}

export class St3Client {
    private readonly baseUrl: string;
    private readonly credential?: ClientOptions['credential'];
    private readonly fetchImpl: typeof fetch;
    private discovered?: EnvelopeOf<Capabilities>;

    constructor(options: ClientOptions) {
        this.baseUrl = options.baseUrl.replace(/\/+$/, '');
        this.credential = options.credential;
        this.fetchImpl = options.fetchImpl ?? fetch;
    }

    async capabilities(): Promise<EnvelopeOf<Capabilities>> {
        const response = await this.request<Capabilities>('GET', '/v1/client/capabilities');
        this.discovered = response;
        return response;
    }

    async discover(): Promise<EnvelopeOf<Capabilities>> {
        return this.discovered ?? this.capabilities();
    }

    private async request<T>(method: 'GET' | 'POST', path: string, body?: unknown): Promise<EnvelopeOf<T>> {
        const credential = await this.credential?.();
        const headers: Record<string, string> = { Accept: 'application/json' };
        if (credential) headers.Authorization = `Bearer ${credential}`;
        if (body !== undefined) headers['Content-Type'] = 'application/json';
        const response = await this.fetchImpl(this.baseUrl + path, {
            method, headers, body: body === undefined ? undefined : JSON.stringify(body),
        });
        const payload: unknown = await response.json();
        if (!payload || typeof payload !== 'object' || (payload as { api_version?: unknown }).api_version !== API_VERSION) {
            throw new Error('Unexpected st3 client API response');
        }
        if (!response.ok || 'error_version' in payload) {
            throw new ClientError(payload as ErrorEnvelope, response.status);
        }
        if (!('snapshot' in payload) || !('value' in payload)) {
            throw new Error('Incomplete st3 client API response');
        }
        return payload as EnvelopeOf<T>;
    }

    private async get<T>(path: string, kind?: 'events'): Promise<EnvelopeOf<T>> {
        const capabilities = await this.discover();
        const url = new URL(path, this.baseUrl + '/');
        const limit = url.searchParams.get('limit');
        if (limit !== null) bounded(Number(limit), kind === 'events' ? capabilities.value.limits.max_event_items : capabilities.value.limits.max_page_items, 'limit');
        const wait = url.searchParams.get('wait_ms');
        if (wait !== null && (!Number.isSafeInteger(Number(wait)) || Number(wait) < 0 || Number(wait) > capabilities.value.limits.max_wait_ms)) {
            throw new RangeError(`wait_ms exceeds negotiated maximum ${capabilities.value.limits.max_wait_ms}`);
        }
        return this.request<T>('GET', path);
    }

    async submitAction(request: ActionRequest): Promise<EnvelopeOf<ActionResult>> {
        await this.discover();
        return this.request<ActionResult>('POST', '/v1/client/actions', request);
    }

    async beginPairing(request: PairingBegin): Promise<EnvelopeOf<PairingChallenge>> {
        return this.request<PairingChallenge>('POST', '/v1/client/pairings', request);
    }

    async completePairing(id: string, request: PairingComplete): Promise<EnvelopeOf<PairedSession>> {
        return this.request<PairedSession>('POST', `/v1/client/pairings/${encodeURIComponent(routedId(id))}/complete`, request);
    }

    async followOperation(id: string, options: { signal?: AbortSignal; intervalMs?: number } = {}): Promise<EnvelopeOf<Resource>> {
        const intervalMs = options.intervalMs ?? 1000;
        if (!Number.isSafeInteger(intervalMs) || intervalMs < 100) throw new RangeError('intervalMs must be at least 100');
        while (true) {
            if (options.signal?.aborted) throw new Error('Operation follow aborted');
            const result = await this.operationsGet(id);
            if (result.value.kind !== 'operation') throw new Error('Operation detail returned another resource kind');
            if (result.value.state === 'completed' || result.value.state === 'failed') return result;
            await new Promise<void>((resolve, reject) => {
                const timer = setTimeout(() => { options.signal?.removeEventListener('abort', onAbort); resolve(); }, intervalMs);
                const onAbort = () => { clearTimeout(timer); reject(new Error('Operation follow aborted')); };
                options.signal?.addEventListener('abort', onAbort, { once: true });
            });
        }
    }

    async nowList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/now' + query(options)); }
    async machinesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/machines' + query(options)); }
    async devicesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/devices' + query(options)); }
    async attentionList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/attention' + query(options)); }
    async attentionGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/attention/${encodeURIComponent(routedId(id))}`); }
    async messagesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/messages' + query(options)); }
    async messagesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/messages/${encodeURIComponent(routedId(id))}`); }
    async launchesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/launches' + query(options)); }
    async launchesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}`); }
    async launchVariantsList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}/variants` + query(options)); }
    async launchDecisionsList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}/decisions` + query(options)); }
    async launchApprovalsList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}/approvals` + query(options)); }
    async missionsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/missions' + query(options)); }
    async missionsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/missions/${encodeURIComponent(routedId(id))}`); }
    async workList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/work' + query(options)); }
    async workGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/work/${encodeURIComponent(routedId(id))}`); }
    async agentsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/agents' + query(options)); }
    async agentsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/agents/${encodeURIComponent(routedId(id))}`); }
    async runtimesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/runtimes' + query(options)); }
    async runtimesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/runtimes/${encodeURIComponent(routedId(id))}`); }
    async terminalsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/terminals' + query(options)); }
    async operationsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/operations' + query(options)); }
    async operationsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/operations/${encodeURIComponent(routedId(id))}`); }
    async historyList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/history' + query(options)); }
    async historyGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/history/${encodeURIComponent(routedId(id))}`); }
    async sessionsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/sessions' + query(options)); }
    async sessionsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/sessions/${encodeURIComponent(routedId(id))}`); }
    async timelineList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<TimelinePage>> { return this.get(`/v1/client/sessions/${encodeURIComponent(routedId(id))}/timeline` + query(options)); }
    async eventsList(options: EventOptions = {}): Promise<EnvelopeOf<EventPage>> { return this.get('/v1/client/events' + query(options), 'events'); }
    async terminalScreen(id: string): Promise<EnvelopeOf<TerminalScreen>> { return this.get(`/v1/client/terminals/${encodeURIComponent(routedId(id))}/screen`); }
    async attentionResolve(input: Omit<ActionOf<'attention.resolve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'attention.resolve' } as ActionOf<'attention.resolve'>); }
    async launchApprove(input: Omit<ActionOf<'launch.approve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.approve' } as ActionOf<'launch.approve'>); }
    async launchCancel(input: Omit<ActionOf<'launch.cancel'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.cancel' } as ActionOf<'launch.cancel'>); }
    async launchCreate(input: Omit<ActionOf<'launch.create'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.create' } as ActionOf<'launch.create'>); }
    async launchPreview(input: Omit<ActionOf<'launch.preview'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.preview' } as ActionOf<'launch.preview'>); }
    async launchRevise(input: Omit<ActionOf<'launch.revise'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.revise' } as ActionOf<'launch.revise'>); }
    async messageClose(input: Omit<ActionOf<'message.close'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'message.close' } as ActionOf<'message.close'>); }
    async messageRead(input: Omit<ActionOf<'message.read'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'message.read' } as ActionOf<'message.read'>); }
    async messageSend(input: Omit<ActionOf<'message.send'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'message.send' } as ActionOf<'message.send'>); }
    async missionApproveRevision(input: Omit<ActionOf<'mission.approve-revision'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.approve-revision' } as ActionOf<'mission.approve-revision'>); }
    async missionCancel(input: Omit<ActionOf<'mission.cancel'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.cancel' } as ActionOf<'mission.cancel'>); }
    async missionCancelRevision(input: Omit<ActionOf<'mission.cancel-revision'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.cancel-revision' } as ActionOf<'mission.cancel-revision'>); }
    async missionRevise(input: Omit<ActionOf<'mission.revise'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.revise' } as ActionOf<'mission.revise'>); }
    async missionStart(input: Omit<ActionOf<'mission.start'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.start' } as ActionOf<'mission.start'>); }
    async pairingRevoke(input: Omit<ActionOf<'pairing.revoke'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'pairing.revoke' } as ActionOf<'pairing.revoke'>); }
    async reviewApprove(input: Omit<ActionOf<'review.approve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'review.approve' } as ActionOf<'review.approve'>); }
    async reviewReject(input: Omit<ActionOf<'review.reject'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'review.reject' } as ActionOf<'review.reject'>); }
    async runtimeContextClear(input: Omit<ActionOf<'runtime.context-clear'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.context-clear' } as ActionOf<'runtime.context-clear'>); }
    async runtimeReset(input: Omit<ActionOf<'runtime.reset'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.reset' } as ActionOf<'runtime.reset'>); }
    async runtimeRestart(input: Omit<ActionOf<'runtime.restart'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.restart' } as ActionOf<'runtime.restart'>); }
    async runtimeSignal(input: Omit<ActionOf<'runtime.signal'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.signal' } as ActionOf<'runtime.signal'>); }
    async runtimeStop(input: Omit<ActionOf<'runtime.stop'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.stop' } as ActionOf<'runtime.stop'>); }
    async sessionImport(input: Omit<ActionOf<'session.import'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'session.import' } as ActionOf<'session.import'>); }
    async terminalAttach(input: Omit<ActionOf<'terminal.attach'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.attach' } as ActionOf<'terminal.attach'>); }
    async terminalDetach(input: Omit<ActionOf<'terminal.detach'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.detach' } as ActionOf<'terminal.detach'>); }
    async terminalInput(input: Omit<ActionOf<'terminal.input'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.input' } as ActionOf<'terminal.input'>); }
    async terminalResize(input: Omit<ActionOf<'terminal.resize'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.resize' } as ActionOf<'terminal.resize'>); }
    async workClaim(input: Omit<ActionOf<'work.claim'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.claim' } as ActionOf<'work.claim'>); }
    async workComplete(input: Omit<ActionOf<'work.complete'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.complete' } as ActionOf<'work.complete'>); }
    async workFail(input: Omit<ActionOf<'work.fail'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.fail' } as ActionOf<'work.fail'>); }
    async workProgress(input: Omit<ActionOf<'work.progress'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.progress' } as ActionOf<'work.progress'>); }
    async workPublishMission(input: Omit<ActionOf<'work.publish-mission'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.publish-mission' } as ActionOf<'work.publish-mission'>); }
    async workRelease(input: Omit<ActionOf<'work.release'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.release' } as ActionOf<'work.release'>); }
    async workRenew(input: Omit<ActionOf<'work.renew'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.renew' } as ActionOf<'work.renew'>); }
}
