// @generated by st3-client-codegen; edit the template, then regenerate.
import { API_VERSION } from './Models.generated';
import type {
    AgentDeclaration, Glass, GlassPut, GlassDelete, ActionOf, ActionRequest, ActionResult, AgentQueue, BlobChunk, BlobUpload, Capabilities, DocumentContent, EnvelopeOf,
    ResourcesFilter, ResourcesPage,
    Arrangement, ArrangementPage,
    SubjectDefinition, UsagePeriod, CollectionName, CollectionFrame,
    ConversationChanges, ConversationSearch, ErrorEnvelope, EventPage, Page, PairingBegin, PairingChallenge,
    PairingComplete, PairedSession, Resource, Snapshot, TerminalScreen, TimelinePage,
} from './Models.generated';

export type PageOptions = { cursor?: string; limit?: number };
export type ListOptions = PageOptions & { history?: boolean; owner_run?: string; actor?: string; status?: string; native_only?: boolean };
export type EventOptions = { after?: string; limit?: number; wait_ms?: number };
export type ClientOptions = {
    baseUrl: string;
    credential?: () => string | undefined | Promise<string | undefined>;
    fetchImpl?: typeof fetch;
};

export const TERMINAL_SUBPROTOCOL = 'st3.client.terminal.v0';
export const CONVERSATION_SUBPROTOCOL = 'st3.client.conversation.v0';
export const COLLECTIONS_SUBPROTOCOL = 'st3.client.collections.v0';

/** The WebSocket surface a terminal stream uses. React Native's WebSocket accepts headers. */
export type TerminalSocket = {
    onmessage: ((event: { data: unknown }) => void) | null;
    onclose: ((event: { code: number; reason: string }) => void) | null;
    onerror: ((event: unknown) => void) | null;
    close(code?: number, reason?: string): void;
};
export type TerminalSocketFactory = (url: string, protocols: string[], headers: Record<string, string>) => TerminalSocket;
export type TerminalStreamOptions = {
    /** The single-use capability from `terminal.attach`. */
    streamCapability: string;
    incarnation?: string;
    /** Each screen replaces every earlier one: the current screen first, then one per change. */
    onScreen: (screen: EnvelopeOf<TerminalScreen>) => void;
    /** Called once when the server ends the stream: without an error after a normal close, or
     * with the server's error, such as `stale-fence` after the runtime incarnation changes. */
    onEnd?: (error?: Error) => void;
    socket?: TerminalSocketFactory;
};
export type TerminalStream = { close(): void };

/** `person` applies to attention, `actor` to work, and `status` to agents. */
export type CollectionFilters = { person?: string | null; actor?: string | null; status?: string | null };
/** The WebSocket surface the collections socket uses: a terminal socket that also sends. */
export type CollectionSocket = TerminalSocket & {
    onopen: (() => void) | null;
    send(data: string): void;
};
export type CollectionSocketFactory = (url: string, protocols: string[], headers: Record<string, string>) => CollectionSocket;
export type CollectionStreamOptions = {
    onFrame: (frame: CollectionFrame) => void;
    /** Called once when the socket ends: without an error after a normal close. Open a new
     * socket and subscribe again; its snapshots are authoritative. */
    onEnd?: (error?: Error) => void;
    socket?: CollectionSocketFactory;
};
export type CollectionStream = {
    /** Hold a window of up to `limit` (1–200) current items. A held ID is replaced. */
    subscribeGlasses(id: string): void;
    subscribeArrangements(id: string, person: string, limit?: number): void;
    subscribe(id: string, collection: Exclude<CollectionName, 'arrangements'>, limit?: number, filters?: CollectionFilters): void;
    /** Follow a terminal with the incarnation and single-use capability `terminal.attach` returned. */
    subscribeTerminal(id: string, terminal: string, incarnation: string | null | undefined, capability: string): void;
    /** Follow the conversation of an agent or a session. */
    subscribeConversation(id: string, conversation: string): void;
    unsubscribe(id: string): void;
    close(): void;
};
/** A window's rows in display order, as `applyWindow` keeps them. */
export type CollectionWindow = { items: Resource[]; hasMore: boolean; snapshot: Snapshot };

/** Apply one `snapshot` or `changes` frame to a window: removals and upserts first, then the
 * frame's complete order. A `changes` frame without an earlier snapshot has nothing to apply to. */
export function applyWindow(window: CollectionWindow | undefined, frame: CollectionFrame): CollectionWindow | undefined {
    if (frame.kind !== 'snapshot' && frame.kind !== 'changes') return window;
    if (frame.kind === 'changes' && !window) return undefined;
    const rows = new Map<string, Resource>(frame.kind === 'snapshot' ? [] : window!.items.map(item => [item.id, item]));
    if (frame.kind === 'changes') for (const id of frame.removes) rows.delete(id);
    for (const item of frame.kind === 'snapshot' ? frame.items : frame.upserts) rows.set(item.id, item);
    const items = frame.order.flatMap(id => rows.get(id) ?? []);
    return { items, hasMore: frame.has_more, snapshot: frame.snapshot };
}

function defaultTerminalSocket(url: string, protocols: string[], headers: Record<string, string>): TerminalSocket {
    const Socket = WebSocket as unknown as new (url: string, protocols: string[], options: { headers: Record<string, string> }) => TerminalSocket;
    return new Socket(url, protocols, { headers });
}

export class ClientError extends Error {
    constructor(public readonly response: ErrorEnvelope, public readonly status: number) {
        super(response.message);
        this.name = 'ClientError';
    }
}

function routedId(id: string): string {
    if (id.startsWith('glass/')) return id.split('/').pop()!;
    return id.replace(/^(launch|session|pairing)\//, '');
}

function query(options: Record<string, string | number | boolean | undefined>): string {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(options)) {
        if (value !== undefined) params.set(key, String(value));
    }
    const result = params.toString();
    return result ? `?${result}` : '';
}

function bounded(value: number | undefined, maximum: number, name: string): void {
    if (value !== undefined && (!Number.isSafeInteger(value) || value < 1 || value > maximum)) {
        throw new RangeError(`${name} must be an integer between 1 and ${maximum}`);
    }
}

export class St3Client {
    private readonly baseUrl: string;
    private readonly credential?: ClientOptions['credential'];
    private readonly fetchImpl: typeof fetch;
    private discovered?: EnvelopeOf<Capabilities>;

    constructor(options: ClientOptions) {
        this.baseUrl = options.baseUrl.replace(/\/+$/, '');
        this.credential = options.credential;
        this.fetchImpl = options.fetchImpl ?? fetch;
    }

    async capabilities(): Promise<EnvelopeOf<Capabilities>> {
        const response = await this.request<Capabilities>('GET', '/v1/client/capabilities');
        this.discovered = response;
        return response;
    }

    async discover(): Promise<EnvelopeOf<Capabilities>> {
        return this.discovered ?? this.capabilities();
    }

    private async request<T>(method: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, body?: unknown, idempotencyKey?: string, raw?: { contentType: string }): Promise<EnvelopeOf<T>> {
        const credential = await this.credential?.();
        const headers: Record<string, string> = { Accept: 'application/json' };
        if (idempotencyKey) headers['Idempotency-Key'] = idempotencyKey;
        if (credential) headers.Authorization = `Bearer ${credential}`;
        if (body !== undefined) headers['Content-Type'] = raw?.contentType ?? 'application/json';
        const response = await this.fetchImpl(this.baseUrl + path, {
            method, headers, body: body === undefined ? undefined : raw ? (body as BodyInit) : JSON.stringify(body),
        });
        const payload: unknown = await response.json();
        if (!payload || typeof payload !== 'object' || (payload as { api_version?: unknown }).api_version !== API_VERSION) {
            throw new Error('Unexpected st client API response');
        }
        if (!response.ok || 'error_version' in payload) {
            throw new ClientError(payload as ErrorEnvelope, response.status);
        }
        if (!('snapshot' in payload) || !('value' in payload)) {
            throw new Error('Incomplete st client API response');
        }
        return payload as EnvelopeOf<T>;
    }

    private async get<T>(path: string, kind?: 'events'): Promise<EnvelopeOf<T>> {
        const capabilities = await this.discover();
        const url = new URL(path, this.baseUrl + '/');
        const limit = url.searchParams.get('limit');
        if (limit !== null) bounded(Number(limit), kind === 'events' ? capabilities.value.limits.max_event_items : capabilities.value.limits.max_page_items, 'limit');
        const wait = url.searchParams.get('wait_ms');
        if (wait !== null && (!Number.isSafeInteger(Number(wait)) || Number(wait) < 0 || Number(wait) > capabilities.value.limits.max_wait_ms)) {
            throw new RangeError(`wait_ms exceeds negotiated maximum ${capabilities.value.limits.max_wait_ms}`);
        }
        return this.request<T>('GET', path);
    }

    /** Keep one image (PNG, JPEG, GIF or WebP, at most 10 MiB) on the member this client talks to. Name the answer's `blob` in a `message.send` attachment. */
    uploadBlob(bytes: Blob | ArrayBuffer | Uint8Array, mediaType: 'image/png' | 'image/jpeg' | 'image/gif' | 'image/webp'): Promise<EnvelopeOf<BlobUpload>> {
        return this.request<BlobUpload>('POST', '/v1/client/blobs', bytes, undefined, { contentType: mediaType });
    }

    /** Up to 512 KiB of an attachment from `offset`, base64 in `data`. */
    blobChunk(sha256: string, options: { message?: string; offset?: number } = {}): Promise<EnvelopeOf<BlobChunk>> {
        const query = new URLSearchParams();
        query.set('offset', String(options.offset ?? 0));
        if (options.message) query.set('message', options.message);
        return this.request<BlobChunk>('GET', `/v1/client/blobs/${encodeURIComponent(sha256)}/chunk?${query}`);
    }

    /** A whole attachment, read in chunks. Pass the message that carries it. */
    async blob(sha256: string, message?: string): Promise<Uint8Array> {
        const parts: Uint8Array[] = [];
        let received = 0;
        for (;;) {
            const chunk = (await this.blobChunk(sha256, { message, offset: received })).value;
            const binary = atob(chunk.data);
            const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
            if (bytes.length === 0 && received < chunk.size) throw new Error('A blob chunk came back empty');
            parts.push(bytes);
            received += bytes.length;
            if (received >= chunk.size) break;
        }
        const whole = new Uint8Array(received);
        let at = 0;
        for (const part of parts) { whole.set(part, at); at += part.length; }
        return whole;
    }

    async submitAction(request: ActionRequest): Promise<EnvelopeOf<ActionResult>> {
        await this.discover();
        return this.request<ActionResult>('POST', '/v1/client/actions', request);
    }

    async beginPairing(request: PairingBegin): Promise<EnvelopeOf<PairingChallenge>> {
        return this.request<PairingChallenge>('POST', '/v1/client/pairings', request);
    }

    async completePairing(id: string, request: PairingComplete): Promise<EnvelopeOf<PairedSession>> {
        return this.request<PairedSession>('POST', `/v1/client/pairings/${encodeURIComponent(routedId(id))}/complete`, request);
    }

    async followOperation(id: string, options: { signal?: AbortSignal; intervalMs?: number } = {}): Promise<EnvelopeOf<Resource>> {
        const intervalMs = options.intervalMs ?? 1000;
        if (!Number.isSafeInteger(intervalMs) || intervalMs < 100) throw new RangeError('intervalMs must be at least 100');
        while (true) {
            if (options.signal?.aborted) throw new Error('Operation follow aborted');
            const result = await this.operationsGet(id);
            if (result.value.kind !== 'operation') throw new Error('Operation detail returned another resource kind');
            if (result.value.state === 'completed' || result.value.state === 'failed') return result;
            await new Promise<void>((resolve, reject) => {
                const timer = setTimeout(() => { options.signal?.removeEventListener('abort', onAbort); resolve(); }, intervalMs);
                const onAbort = () => { clearTimeout(timer); reject(new Error('Operation follow aborted')); };
                options.signal?.addEventListener('abort', onAbort, { once: true });
            });
        }
    }

    /** Open the terminal stream that one `terminal.attach` capability allows. */
    async terminalStream(id: string, options: TerminalStreamOptions): Promise<TerminalStream> {
        const credential = await this.credential?.();
        const url = new URL(`${this.baseUrl}/v1/client/terminals/${encodeURIComponent(routedId(id))}/stream`);
        url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:';
        if (options.incarnation) url.searchParams.set('incarnation', options.incarnation);
        const headers: Record<string, string> = {};
        if (credential) headers.Authorization = `Bearer ${credential}`;
        const socket = (options.socket ?? defaultTerminalSocket)(url.toString(), [TERMINAL_SUBPROTOCOL, `st3.cap.${options.streamCapability}`], headers);
        let ended = false;
        const stop = () => { ended = true; socket.onmessage = null; socket.onclose = null; socket.onerror = null; };
        const end = (error?: Error) => { if (ended) return; stop(); options.onEnd?.(error); };
        const fail = (error: Error) => { end(error); socket.close(1000); };
        socket.onmessage = event => {
            let payload: unknown;
            try { payload = JSON.parse(String(event.data)); } catch { fail(new Error('A terminal stream message is not JSON')); return; }
            if (!payload || typeof payload !== 'object' || (payload as { api_version?: unknown }).api_version !== API_VERSION) { fail(new Error('Unexpected st terminal stream message')); return; }
            if ('error_version' in payload) { fail(new ClientError(payload as ErrorEnvelope, 0)); return; }
            const screen = payload as EnvelopeOf<TerminalScreen>;
            if (screen.value?.kind !== 'terminal-screen') { fail(new Error('A terminal stream message is not a screen')); return; }
            options.onScreen(screen);
        };
        socket.onclose = event => end(event.code === 1000 ? undefined : new Error(`The terminal stream closed (${event.code}${event.reason ? ` ${event.reason}` : ''})`));
        socket.onerror = () => end(new Error('The terminal stream failed'));
        return { close: () => { if (!ended) { stop(); socket.close(1000); } } };
    }

    async conversationStream(id: string, options: { after?: string; onChange: (change: EnvelopeOf<ConversationChanges>) => void; onEnd?: (error?: Error) => void; socket?: TerminalSocketFactory }): Promise<TerminalStream> {
        const credential = await this.credential?.();
        const url = new URL(`${this.baseUrl}/v1/client/conversations/${encodeURIComponent(routedId(id))}/stream`);
        url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:';
        if (options.after) url.searchParams.set('after', options.after);
        const headers: Record<string, string> = {};
        if (credential) headers.Authorization = `Bearer ${credential}`;
        const socket = (options.socket ?? defaultTerminalSocket)(url.toString(), [CONVERSATION_SUBPROTOCOL], headers);
        let ended = false;
        const end = (error?: Error) => { if (ended) return; ended = true; socket.onmessage = null; socket.onclose = null; socket.onerror = null; options.onEnd?.(error); };
        socket.onmessage = event => {
            try {
                const payload = JSON.parse(String(event.data)) as EnvelopeOf<ConversationChanges> | ErrorEnvelope;
                if (!payload || payload.api_version !== API_VERSION) throw new Error('Unexpected st conversation stream message');
                if ('error_version' in payload) throw new ClientError(payload, 0);
                if (payload.value?.kind !== 'conversation-changes') throw new Error('A conversation stream message is not a change');
                options.onChange(payload);
            } catch (error) { end(error as Error); socket.close(1000); }
        };
        socket.onclose = event => end(event.code === 1000 ? undefined : new Error(`The conversation stream closed (${event.code})`));
        socket.onerror = () => end(new Error('The conversation stream failed'));
        return { close: () => { if (!ended) { ended = true; socket.close(1000); } } };
    }

    /** Open the one collections socket. Commands sent before it opens wait for it. */
    async collectionStream(options: CollectionStreamOptions): Promise<CollectionStream> {
        const credential = await this.credential?.();
        const url = new URL(`${this.baseUrl}/v1/client/collections/stream`);
        url.protocol = url.protocol === 'https:' ? 'wss:' : 'ws:';
        const headers: Record<string, string> = {};
        if (credential) headers.Authorization = `Bearer ${credential}`;
        const socket = (options.socket ?? (defaultTerminalSocket as unknown as CollectionSocketFactory))(url.toString(), [COLLECTIONS_SUBPROTOCOL], headers);
        let ended = false, open = false;
        const waiting: string[] = [];
        const stop = () => { ended = true; socket.onopen = null; socket.onmessage = null; socket.onclose = null; socket.onerror = null; };
        const end = (error?: Error) => { if (ended) return; stop(); options.onEnd?.(error); };
        const send = (command: Record<string, unknown>) => {
            if (ended) return;
            const text = JSON.stringify(command);
            if (open) socket.send(text); else waiting.push(text);
        };
        socket.onopen = () => { open = true; for (const text of waiting.splice(0)) socket.send(text); };
        socket.onmessage = event => {
            let frame: CollectionFrame;
            try { frame = JSON.parse(String(event.data)) as CollectionFrame; } catch { end(new Error('A collections message is not JSON')); socket.close(1000); return; }
            if (!frame || typeof frame !== 'object' || typeof frame.kind !== 'string') { end(new Error('Unexpected st collections message')); socket.close(1000); return; }
            options.onFrame(frame);
        };
        socket.onclose = event => end(event.code === 1000 ? undefined : new Error(`The collections socket closed (${event.code}${event.reason ? ` ${event.reason}` : ''})`));
        socket.onerror = () => end(new Error('The collections socket failed'));
        return {
            subscribeGlasses: id => send({kind: 'subscribe', id, collection: 'glasses', limit: 100}),
            subscribeArrangements: (id, person, limit = 100) => send({kind: 'subscribe', id, collection: 'arrangements', person, limit}),
            subscribe: (id, collection, limit, filters = {}) => send({ kind: 'subscribe', id, collection, ...(limit === undefined ? {} : { limit }), ...filters }),
            subscribeTerminal: (id, terminal, incarnation, capability) => send({ kind: 'subscribe', id, collection: 'terminal', terminal, incarnation, capability }),
            subscribeConversation: (id, conversation) => send({ kind: 'subscribe', id, collection: 'conversation', conversation }),
            unsubscribe: id => send({ kind: 'unsubscribe', id }),
            close: () => { if (!ended) { stop(); socket.close(1000); } },
        };
    }

    listGlasses(options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/glasses${query(options)}`); }
    getGlass(id: string): Promise<EnvelopeOf<Glass>> { return this.get(`/v1/client/glasses/${encodeURIComponent(id.split('/').pop()!)}`); }
    putGlass(id: string, request: GlassPut, idempotencyKey: string): Promise<EnvelopeOf<Glass>> { return this.request('PUT', `/v1/client/glasses/${encodeURIComponent(id.split('/').pop()!)}`, request, idempotencyKey); }
    deleteGlass(id: string, request: GlassDelete, idempotencyKey: string): Promise<EnvelopeOf<Glass>> { return this.request('DELETE', `/v1/client/glasses/${encodeURIComponent(id.split('/').pop()!)}`, request, idempotencyKey); }
    async hostRepositories(id: string): Promise<EnvelopeOf<HostRepositories>> { return this.get(`/v1/client/hosts/${encodeURIComponent(routedId(id))}/repositories`); }
    async setsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/sets' + query(options)); }
    async setsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/sets/${encodeURIComponent(routedId(id))}`); }
    async documentGet(name: string): Promise<EnvelopeOf<DocumentContent>> { return this.get('/v1/client/documents/content' + query({ name })); }
    async subjectDefinition(subject: string, showEnvValues = false): Promise<EnvelopeOf<SubjectDefinition>> { return this.get('/v1/client/subject-definition' + query({ subject, show_env_values: showEnvValues })); }
    async usagePeriod(options: { since_ms?: number; until_ms?: number } = {}): Promise<EnvelopeOf<UsagePeriod>> { return this.get('/v1/client/usage' + query(options)); }
    async nowList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/now' + query(options)); }
    async machinesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/machines' + query(options)); }
    async devicesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/devices' + query(options)); }
    async attentionList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/attention' + query(options)); }
    async attentionGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/attention/${encodeURIComponent(routedId(id))}`); }
    async messagesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/messages' + query(options)); }
    async messagesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/messages/${encodeURIComponent(routedId(id))}`); }
    async launchesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/launches' + query(options)); }
    async launchesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}`); }
    async launchVariantsList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}/variants` + query(options)); }
    async launchDecisionsList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}/decisions` + query(options)); }
    async launchApprovalsList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<Page>> { return this.get(`/v1/client/launches/${encodeURIComponent(routedId(id))}/approvals` + query(options)); }
    async missionsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/missions' + query(options)); }
    async missionsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/missions/${encodeURIComponent(routedId(id))}`); }
    async workList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/work' + query(options)); }
    async workGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/work/${encodeURIComponent(routedId(id))}`); }
    async resourcesList(filters: ResourcesFilter = {}, options: PageOptions = {}): Promise<EnvelopeOf<ResourcesPage>> { return this.get('/v1/client/resources' + query({ ...filters, ...options })); }
    async agentsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/agents' + query(options)); }
    async agentsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/agents/${encodeURIComponent(routedId(id))}`); }
    async agentDeclarationGet(id: string, revision?: string, showEnvValues = false): Promise<EnvelopeOf<AgentDeclaration>> { return this.get(`/v1/client/agent-declarations/${encodeURIComponent(routedId(id))}` + query({ revision, show_env_values: showEnvValues })); }
    async agentQueueGet(id: string): Promise<EnvelopeOf<AgentQueue>> { return this.get(`/v1/client/agent-queues/${encodeURIComponent(routedId(id))}`); }
    async runtimesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/runtimes' + query(options)); }
    async runtimesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/runtimes/${encodeURIComponent(routedId(id))}`); }
    async observersList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/observers' + query(options)); }
    async observersGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/observers/${encodeURIComponent(routedId(id))}`); }
    async subscriptionsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/subscriptions' + query(options)); }
    async subscriptionsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/subscriptions/${encodeURIComponent(routedId(id))}`); }
    async lanesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/lanes' + query(options)); }
    async lanesGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/lanes/${encodeURIComponent(routedId(id))}`); }
    async terminalsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/terminals' + query(options)); }
    async operationsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/operations' + query(options)); }
    async operationsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/operations/${encodeURIComponent(routedId(id))}`); }
    async historyList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/history' + query(options)); }
    async historyGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/history/${encodeURIComponent(routedId(id))}`); }
    async sessionsList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/sessions' + query(options)); }
    async sessionsGet(id: string): Promise<EnvelopeOf<Resource>> { return this.get(`/v1/client/sessions/${encodeURIComponent(routedId(id))}`); }
    async conversationSearch(text: string, options: { agent?: string; since?: string; cursor?: string; limit?: number } = {}): Promise<EnvelopeOf<ConversationSearch>> { return this.get('/v1/client/conversations/search' + query({ text, ...options })); }
    async timelineList(id: string, options: PageOptions = {}): Promise<EnvelopeOf<TimelinePage>> { return this.get(`/v1/client/sessions/${encodeURIComponent(routedId(id))}/timeline` + query(options)); }
    async conversationChanges(id: string, options: { after?: string; wait_ms?: number } = {}): Promise<EnvelopeOf<ConversationChanges>> { return this.get(`/v1/client/conversations/${encodeURIComponent(routedId(id))}/changes` + query(options)); }
    async eventsList(options: EventOptions = {}): Promise<EnvelopeOf<EventPage>> { return this.get('/v1/client/events' + query(options), 'events'); }
    async terminalScreen(id: string): Promise<EnvelopeOf<TerminalScreen>> { return this.get(`/v1/client/terminals/${encodeURIComponent(routedId(id))}/screen`); }
    async arrangementsList(person: string, options: PageOptions = {}): Promise<EnvelopeOf<ArrangementPage>> { return this.get('/v1/client/arrangements' + query({ person, ...options })); }
    async arrangementsGet(personName: string, uuid: string): Promise<EnvelopeOf<Arrangement>> { return this.get(`/v1/client/arrangements/${encodeURIComponent(personName)}/${encodeURIComponent(uuid)}`); }
    async glassesList(options: ListOptions = {}): Promise<EnvelopeOf<Page>> { return this.get('/v1/client/glasses' + query(options)); }
    async glassesGet(id: string): Promise<EnvelopeOf<Glass>> { return this.get(`/v1/client/glasses/${encodeURIComponent(routedId(id))}`); }
    async agentCreate(input: Omit<ActionOf<'agent.create'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'agent.create' } as ActionOf<'agent.create'>); }
    async agentQueueMove(input: Omit<ActionOf<'agent.queue-move'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'agent.queue-move' } as ActionOf<'agent.queue-move'>); }
    async agentResume(input: Omit<ActionOf<'agent.resume'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'agent.resume' } as ActionOf<'agent.resume'>); }
    async agentStart(input: Omit<ActionOf<'agent.start'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'agent.start' } as ActionOf<'agent.start'>); }
    async agentStop(input: Omit<ActionOf<'agent.stop'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'agent.stop' } as ActionOf<'agent.stop'>); }
    async agentSuspend(input: Omit<ActionOf<'agent.suspend'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'agent.suspend' } as ActionOf<'agent.suspend'>); }
    async arrangementEdit(input: Omit<ActionOf<'arrangement.edit'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'arrangement.edit' } as ActionOf<'arrangement.edit'>); }
    async attentionResolve(input: Omit<ActionOf<'attention.resolve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'attention.resolve' } as ActionOf<'attention.resolve'>); }
    async laneApprove(input: Omit<ActionOf<'lane.approve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'lane.approve' } as ActionOf<'lane.approve'>); }
    async laneJoin(input: Omit<ActionOf<'lane.join'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'lane.join' } as ActionOf<'lane.join'>); }
    async laneLeave(input: Omit<ActionOf<'lane.leave'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'lane.leave' } as ActionOf<'lane.leave'>); }
    async laneMark(input: Omit<ActionOf<'lane.mark'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'lane.mark' } as ActionOf<'lane.mark'>); }
    async laneMove(input: Omit<ActionOf<'lane.move'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'lane.move' } as ActionOf<'lane.move'>); }
    async launchApprove(input: Omit<ActionOf<'launch.approve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.approve' } as ActionOf<'launch.approve'>); }
    async launchCancel(input: Omit<ActionOf<'launch.cancel'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.cancel' } as ActionOf<'launch.cancel'>); }
    async launchCreate(input: Omit<ActionOf<'launch.create'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.create' } as ActionOf<'launch.create'>); }
    async launchPreview(input: Omit<ActionOf<'launch.preview'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.preview' } as ActionOf<'launch.preview'>); }
    async launchRevise(input: Omit<ActionOf<'launch.revise'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'launch.revise' } as ActionOf<'launch.revise'>); }
    async messageClose(input: Omit<ActionOf<'message.close'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'message.close' } as ActionOf<'message.close'>); }
    async messageRead(input: Omit<ActionOf<'message.read'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'message.read' } as ActionOf<'message.read'>); }
    async messageSend(input: Omit<ActionOf<'message.send'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'message.send' } as ActionOf<'message.send'>); }
    async missionApproveRevision(input: Omit<ActionOf<'mission.approve-revision'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.approve-revision' } as ActionOf<'mission.approve-revision'>); }
    async missionCancel(input: Omit<ActionOf<'mission.cancel'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.cancel' } as ActionOf<'mission.cancel'>); }
    async missionCancelRevision(input: Omit<ActionOf<'mission.cancel-revision'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.cancel-revision' } as ActionOf<'mission.cancel-revision'>); }
    async missionRevise(input: Omit<ActionOf<'mission.revise'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.revise' } as ActionOf<'mission.revise'>); }
    async missionStart(input: Omit<ActionOf<'mission.start'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'mission.start' } as ActionOf<'mission.start'>); }
    async pairingRevoke(input: Omit<ActionOf<'pairing.revoke'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'pairing.revoke' } as ActionOf<'pairing.revoke'>); }
    async reviewApprove(input: Omit<ActionOf<'review.approve'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'review.approve' } as ActionOf<'review.approve'>); }
    async reviewReject(input: Omit<ActionOf<'review.reject'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'review.reject' } as ActionOf<'review.reject'>); }
    async reviewRequestChanges(input: Omit<ActionOf<'review.request-changes'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'review.request-changes' } as ActionOf<'review.request-changes'>); }
    async runtimeContextClear(input: Omit<ActionOf<'runtime.context-clear'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.context-clear' } as ActionOf<'runtime.context-clear'>); }
    async runtimeReset(input: Omit<ActionOf<'runtime.reset'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.reset' } as ActionOf<'runtime.reset'>); }
    async runtimeRestart(input: Omit<ActionOf<'runtime.restart'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.restart' } as ActionOf<'runtime.restart'>); }
    async runtimeSignal(input: Omit<ActionOf<'runtime.signal'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.signal' } as ActionOf<'runtime.signal'>); }
    async runtimeStop(input: Omit<ActionOf<'runtime.stop'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'runtime.stop' } as ActionOf<'runtime.stop'>); }
    async sessionImport(input: Omit<ActionOf<'session.import'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'session.import' } as ActionOf<'session.import'>); }
    async terminalAttach(input: Omit<ActionOf<'terminal.attach'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.attach' } as ActionOf<'terminal.attach'>); }
    async terminalCreate(input: Omit<ActionOf<'terminal.create'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.create' } as ActionOf<'terminal.create'>); }
    async terminalDetach(input: Omit<ActionOf<'terminal.detach'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.detach' } as ActionOf<'terminal.detach'>); }
    async terminalEnd(input: Omit<ActionOf<'terminal.end'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.end' } as ActionOf<'terminal.end'>); }
    async terminalInput(input: Omit<ActionOf<'terminal.input'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.input' } as ActionOf<'terminal.input'>); }
    async terminalResize(input: Omit<ActionOf<'terminal.resize'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'terminal.resize' } as ActionOf<'terminal.resize'>); }
    async workAsk(input: Omit<ActionOf<'work.ask'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.ask' } as ActionOf<'work.ask'>); }
    async workCancelAsk(input: Omit<ActionOf<'work.cancel-ask'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.cancel-ask' } as ActionOf<'work.cancel-ask'>); }
    async workClaim(input: Omit<ActionOf<'work.claim'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.claim' } as ActionOf<'work.claim'>); }
    async workComplete(input: Omit<ActionOf<'work.complete'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.complete' } as ActionOf<'work.complete'>); }
    async workDone(input: Omit<ActionOf<'work.done'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.done' } as ActionOf<'work.done'>); }
    async workFail(input: Omit<ActionOf<'work.fail'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.fail' } as ActionOf<'work.fail'>); }
    async workProgress(input: Omit<ActionOf<'work.progress'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.progress' } as ActionOf<'work.progress'>); }
    async workPublishMission(input: Omit<ActionOf<'work.publish-mission'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.publish-mission' } as ActionOf<'work.publish-mission'>); }
    async workRelease(input: Omit<ActionOf<'work.release'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.release' } as ActionOf<'work.release'>); }
    async workRenew(input: Omit<ActionOf<'work.renew'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.renew' } as ActionOf<'work.renew'>); }
    async workRetry(input: Omit<ActionOf<'work.retry'>, 'api_version' | 'type'>): Promise<EnvelopeOf<ActionResult>> { return this.submitAction({ ...input, api_version: API_VERSION, type: 'work.retry' } as ActionOf<'work.retry'>); }
}
