// @generated by st3-client-codegen; contract sha256 71c0b1bb386208d3de96e00e00be94669b9668d8843647e758f689585578a584
// Source: docs/st3/client-v0/schemas/client-v0.schema.json

export const CONTRACT_SHA256 = '71c0b1bb386208d3de96e00e00be94669b9668d8843647e758f689585578a584' as const;
export const API_VERSION = 'st3.client.v0' as const;

export type ActionCommon = {
  api_version: "st3.client.v0";
  fence: Fence;
  id: Id;
  idempotency_key: string;
  parameters: {

};
  type: "arrangement.edit" | "attention.resolve" | "review.approve" | "review.reject" | "review.request-changes" | "message.send" | "message.read" | "message.close" | "launch.create" | "launch.revise" | "launch.preview" | "launch.approve" | "launch.cancel" | "mission.start" | "mission.revise" | "mission.approve-revision" | "mission.cancel-revision" | "mission.cancel" | "session.import" | "work.ask" | "work.done" | "work.cancel-ask" | "work.claim" | "work.renew" | "work.progress" | "work.complete" | "work.fail" | "work.release" | "work.retry" | "work.publish-mission" | "agent.create" | "agent.stop" | "agent.start" | "agent.suspend" | "agent.resume" | "terminal.create" | "terminal.end" | "agent.queue-move" | "lane.join" | "lane.leave" | "lane.move" | "lane.mark" | "lane.approve" | "runtime.stop" | "runtime.restart" | "runtime.reset" | "runtime.context-clear" | "runtime.signal" | "terminal.input" | "terminal.resize" | "terminal.attach" | "terminal.detach" | "pairing.revoke";
};

export type ActionResult = {
  action_id: Id;
  affected_ids: Array<Id>;
  arrangement_revision?: Revision;
  kind: "action-result";
  operation_id: Id;
  snapshot_id: Id;
  status: "accepted" | "completed" | "rejected";
  terminal_attachment?: (TerminalAttachment | null);
};

export type ActorRef = string;

export type Agent = ResourceHeader & {
  active_work_count?: number;
  ask?: string | null;
  blocked_on?: string | null;
  current_session_id?: string | null;
  current_work?: Array<WorkLabel>;
  current_work_ids?: Array<StepRunId>;
  delivery?: (AgentDelivery | null);
  driver?: string | null;
  fault?: string | null;
  harness_state?: string | null;
  host_id?: (HostId | null);
  id?: AgentId;
  incarnation_id?: string | null;
  kind: "agent";
  last_activity_at?: (Timestamp | null);
  name: string;
  next_work?: (WorkLabel | null);
  next_work_id?: (Id | null);
  owner_run_id?: (MissionRunId | null);
  queued_work_count?: number;
  reachability: AgentReachability;
  reason?: string | null;
  runtime_ids: Array<RuntimeId>;
  silent_since?: (Timestamp | null);
  state: AgentState;
  subagents?: Array<AgentSubagent>;
  suspension?: (AgentSuspension | null);
  todo?: (AgentTodo | null);
  under?: Array<AgentRelationship>;
  upcoming_work?: Array<WorkLabel>;
  upcoming_work_ids?: Array<Id>;
  usage?: (UsageSummary | null);
};

export type AgentCreateParameters = {
  base?: string;
  branch?: string;
  description?: string;
  effort?: string;
  harness: "claude" | "codex" | "pi" | "omp" | "opencode";
  host?: string;
  message?: string;
  model?: string;
  name: string;
  remove_at_run_end?: boolean;
  repo?: string;
  workspace?: string;
};

export type AgentDeclaration = {
  id: Id;
  kdl: string;
  revision: string;
  revisions: Array<string>;
  tree: {

};
};

export type AgentDelivery = {
  polled_seconds_ago?: number | null;
  reason?: string | null;
  state: "current" | "outdated" | "legacy" | "stale" | "unknown";
  transport?: string | null;
};

export type AgentId = string;

export type AgentQueue = {
  agent_id: Id;
  current_work_ids: Array<Id>;
  kind: "agent-queue";
  move_count: number;
  moves: Array<AgentQueueMove>;
  next_work_id: (Id | null);
  runs: Array<AgentQueueRun>;
};

export type AgentQueueMove = {
  actor_id: (Id | null);
  anchor_run_id: (Id | null);
  claim_id: string;
  mission_run_id: Id;
  moved_at: Timestamp;
  placement: "top" | "bottom" | "before" | "after";
  reason: string | null;
};

export type AgentQueueRun = {
  claimed_work_ids: Array<Id>;
  joined_at: Timestamp;
  mission_run_id: Id;
  position: number;
  ready_work_ids: Array<Id>;
  run_state: string;
  state: "claimed" | "ready" | "waiting";
  waiting_for_run_id?: (Id | null);
  waiting_work_ids: Array<Id>;
};

export type AgentReachability = ("local" | "remote" | "unreachable" | "unknown" | "reachable" | "indeterminate" | string);

export type AgentRelationship = {
  agent_id: Id;
  reason?: string | null;
};

export type AgentRepository = {
  agent_ids: Array<string>;
  path: string;
  workspaces: Array<string>;
};

export type AgentResumeParameters = {
  agent: Id;
};

export type AgentStartParameters = {
  agent: Id;
};

export type AgentState = ("desired" | "starting" | "running" | "waiting" | "stopped" | "failed" | "suspended" | string);

export type AgentStopParameters = {
  agent: Id;
  reason?: string;
};

export type AgentSubagent = {
  description?: string | null;
  driver: string;
  id: string;
  lease_expires_at: Timestamp;
  session_id?: string | null;
  started_at?: (Timestamp | null);
  subagent_type?: string | null;
  work_id?: (Id | null);
};

export type AgentSuspendParameters = {
  agent: Id;
  reason?: string;
};

export type AgentSuspension = {
  action: "suspend" | "resume";
  blocking: Array<string>;
  code?: string | null;
  harness?: string | null;
  incarnation_id?: string | null;
  native_session_id?: string | null;
  operation_id: string;
  phase: "quiescing" | "snapshotting" | "suspended" | "failed" | "restoring" | "verifying" | "resumed";
  reason?: string | null;
  suspended_at?: (Timestamp | null);
  updated_at: Timestamp;
};

export type AgentTodo = {
  accepted_at: Timestamp;
  claim_id: string;
  snapshot: HarnessTodoSnapshot;
  stale: boolean;
};

export type Arrangement = ResourceHeader & {
  body: ArrangementBody;
  deleted: false;
  kind: "arrangement";
  owner: ArrangementPerson;
  resolved?: ArrangementResolved;
};

export type ArrangementBody = {
  folders: {
  [key: string]: ArrangementFolder;
};
  name: ArrangementNameRegister;
  placements: {
  [key: string]: ArrangementPlacementRegister;
};
  version: 1;
};

export type ArrangementEditParameters = {
  operations: Array<ArrangementOperation>;
  owner: ArrangementPerson;
  subject: ArrangementId;
};

export type ArrangementFolder = {
  name: ArrangementNameRegister;
  position: ArrangementPositionRegister;
  tombstone: (ArrangementTombstoneRegister | null);
};

export type ArrangementFolderId = string;

export type ArrangementId = string;

export type ArrangementKey = string;

export type ArrangementName = string;

export type ArrangementNameRegister = {
  revision: Revision;
  value: ArrangementName;
};

export type ArrangementOperation = ({
  name: ArrangementName;
  op: "create";
} | {
  name: ArrangementName;
  op: "rename";
} | {
  id: ArrangementFolderId;
  key: ArrangementKey;
  name: ArrangementName;
  op: "folder.create";
  parent: (ArrangementFolderId | null);
} | {
  id: ArrangementFolderId;
  name: ArrangementName;
  op: "folder.rename";
} | {
  id: ArrangementFolderId;
  key: ArrangementKey;
  op: "folder.move";
  parent: (ArrangementFolderId | null);
} | {
  id: ArrangementFolderId;
  op: "folder.delete";
} | {
  folder: (ArrangementFolderId | null);
  key: ArrangementKey;
  op: "subject.place";
  subject: ArrangementSubject;
} | {
  op: "retire";
});

export type ArrangementPage = {
  collection: "arrangements";
  filters: {
  [key: string]: string;
};
  items: Array<Arrangement>;
  kind: "page";
  page: PageInfo;
  replicated?: ReplicatedNotice;
  sync?: SyncNotice;
};

export type ArrangementPerson = string;

export type ArrangementPlacement = {
  folder: (ArrangementFolderId | null);
  key: ArrangementKey;
};

export type ArrangementPlacementRegister = {
  revision: Revision;
  value: ArrangementPlacement;
};

export type ArrangementPosition = {
  key: ArrangementKey;
  parent: (ArrangementFolderId | null);
};

export type ArrangementPositionRegister = {
  revision: Revision;
  value: ArrangementPosition;
};

export type ArrangementResolved = {
  folders: {
  [key: string]: (ArrangementFolderId | null);
};
  parents: {
  [key: string]: (ArrangementFolderId | null);
};
};

export type ArrangementSubject = string;

export type ArrangementTombstoneRegister = {
  revision: Revision;
  value: true;
};

export type Attachment = {
  blob: string;
  media_type: "image/png" | "image/jpeg" | "image/gif" | "image/webp";
  name?: string | null;
  origin: Id;
  sha256: string;
  size: number;
};

export type AttachmentInput = {
  blob: string;
  media_type: "image/png" | "image/jpeg" | "image/gif" | "image/webp";
  name?: string;
};

export type Attention = ResourceHeader & {
  action_parameters?: {

};
  actions: Array<"work.done" | "review.approve" | "review.reject" | "review.request-changes" | "launch.approve" | "launch.cancel" | "mission.approve-revision" | "mission.cancel-revision" | "message.read">;
  attention_kind: "human-gate" | "launch-approval" | "revision-approval" | "unread-message" | "person-step" | "agent-request" | "fault";
  because?: string;
  detail: string;
  episode?: string;
  fix?: {

};
  kind: "attention";
  launch_id?: Id;
  message_id?: Id;
  mission_id?: Id;
  mission_run_id?: Id;
  person_id: Id;
  preview?: (LaunchPreview | null);
  preview_token?: string | null;
  priority: "critical" | "high" | "normal" | "low";
  request?: StructuredRequest;
  requested_at: Timestamp;
  requester_id?: Id;
  review_mode?: "approve" | "feedback";
  source_id: Id;
  source_kind?: string;
  state: "open" | "resolved";
  step_run_id?: Id;
  target_states?: Array<AttentionTargetState>;
  targets?: Array<Id>;
  title: string;
  update?: PersonUpdate;
  variant_id?: Id;
  what?: string;
};

export type AttentionTargetState = {
  id: Id;
  since?: Timestamp;
  state: string;
};

export type BlobChunk = {
  data: string;
  offset: number;
  sha256: string;
  size: number;
};

export type BlobUpload = {
  blob: string;
  media_type: "image/png" | "image/jpeg" | "image/gif" | "image/webp";
  sha256: string;
  size: number;
};

export type CanonicalNode = {
  arguments?: Array<string | number | boolean | null>;
  children?: Array<CanonicalNode>;
  name: string;
  properties?: {
  [key: string]: string | number | boolean | null;
};
};

export type Capabilities = {
  capabilities: Array<Capability>;
  event_cursor: Cursor;
  kind: "capabilities";
  limits: {
  max_arrangement_body_bytes?: number;
  max_arrangement_folders?: number;
  max_arrangement_key_bytes?: number;
  max_arrangement_name_bytes?: number;
  max_arrangement_operations?: number;
  max_arrangement_placements?: number;
  max_arrangement_resource_bytes?: number;
  max_arrangements?: number;
  max_event_items: number;
  max_glass_body_bytes?: number;
  max_glass_depth?: number;
  max_glass_nodes?: number;
  max_glasses?: number;
  max_page_items: number;
  max_response_bytes: number;
  max_wait_ms: number;
};
  machine_version?: string;
  oldest_event_cursor: Cursor;
  schemas: Array<string>;
  session_actor: Id;
  transport: "unix" | "fabric-loopback";
};

export type Capability = {
  id: string;
  state: "granted" | "ungranted" | "unavailable" | "unsupported";
  version: number;
};

export type CollectionCommand = ({
  actor?: string | null;
  collection: "missions" | "attention" | "agents" | "work" | "glasses";
  id: string;
  kind: "subscribe";
  limit?: number;
  person?: string | null;
  status?: string | null;
} | {
  collection: "arrangements";
  id: string;
  kind: "subscribe";
  limit?: number;
  person: ArrangementPerson;
} | {
  capability: string;
  collection: "terminal";
  id: string;
  incarnation?: string | null;
  kind: "subscribe";
  terminal: Id;
} | {
  collection: "conversation";
  conversation: Id;
  id: string;
  kind: "subscribe";
} | {
  id: string;
  kind: "unsubscribe";
});

export type CollectionFrame = ({
  collection: CollectionName;
  has_more: boolean;
  id: string;
  items: Array<Resource>;
  kind: "snapshot";
  order: Array<Id>;
  snapshot: Snapshot;
} | {
  collection: CollectionName;
  has_more: boolean;
  id: string;
  kind: "changes";
  order: Array<Id>;
  removes: Array<Id>;
  snapshot: Snapshot;
  upserts: Array<Resource>;
} | {
  collection: "terminal";
  id: string;
  kind: "screen";
  snapshot: Snapshot;
  value: TerminalScreen;
} | {
  collection: "conversation";
  has_more?: boolean;
  id: string;
  items: Array<TimelineEntry>;
  kind: "conversation";
  replace: boolean;
  session_id: Id;
} | {
  code?: string;
  collection?: string;
  id: string;
  kind: "resync";
  message?: string;
  retryable?: boolean;
} | {
  code?: string;
  collection?: string;
  id?: string;
  kind: "error";
  message: string;
  retryable?: boolean;
});

export type CollectionName = "missions" | "attention" | "agents" | "work" | "glasses" | "arrangements";

export type ConversationChanges = {
  items: Array<TimelineEntry>;
  kind: "conversation-changes";
  next_cursor: Cursor;
  session_id: Id;
};

export type ConversationSearch = {
  host_id: Id;
  incomplete_sources: Array<string>;
  indexed_at: Timestamp;
  items: Array<ConversationSearchHit>;
  kind: "conversation-search";
  page: PageInfo;
  refreshing: boolean;
};

export type ConversationSearchHit = {
  agent_id: string | null;
  conversation_id: Id;
  entry_id: Id;
  entry_type: string;
  excerpt: string;
  timestamp: Timestamp;
};

export type Cursor = string;

export type DecisionOption = {
  description?: string | null;
  id: string;
  label: string;
};

export type DecisionResponse = ({
  type: "boolean";
  value: boolean;
} | {
  type: "single-choice";
  value: string;
} | {
  type: "multiple-choice";
  value: Array<string>;
} | {
  type: "rank";
  value: Array<string>;
});

export type Device = ResourceHeader & {
  expires_at: Timestamp;
  kind: "device";
  name?: string | null;
  person_id: Id;
  scopes: Array<string>;
  session_actor: Id;
  state: "active" | "expired" | "revoked";
};

export type DeviceSignature = {
  chain: Array<string>;
  format: "fields-v1";
  key: string;
  nonce: string;
  signature: string;
  signed_at_unix_ms: number;
  signed_fields: Array<string>;
  signer: string;
};

export type Diagnostic = {
  code: string;
  message: string;
  path?: string | null;
  severity: "info" | "warning" | "error";
};

export type DocumentContent = {
  bytes: Array<number>;
  reference: string;
};

export type Envelope = {
  api_version: "st3.client.v0";
  request_id: RequestId;
  snapshot: Snapshot;
  value: (Capabilities | DocumentContent | SubjectDefinition | Page | ResourcesPage | Resource | TimelinePage | ConversationChanges | ConversationSearch | EventPage | ActionResult | PairingChallenge | PairedSession | TerminalScreen | AgentQueue | UsagePeriod);
};

export type ErrorCode = ("attention-migrated" | "not-found" | "forbidden" | "unsupported-capability" | "validation-failed" | "idempotency-conflict" | "stale-fence" | "cursor-gap" | "page-cursor-expired" | "rate-limited" | "runtime-not-local" | "runtime-authority-indeterminate" | "remote-unavailable" | "terminal-unavailable" | "terminal-ended" | "timeline-history-incomplete" | "blob-too-large" | "unsupported-media-type" | "blob-content-mismatch" | "blob-quota-exceeded" | "blob-not-found" | "blob-expired" | "internal" | string);

export type ErrorEnvelope = {
  api_version: "st3.client.v0";
  code: ErrorCode;
  details: {

};
  error_version: "st3.client.error.v0";
  message: string;
  request_id: Id;
  retry_after_ms?: number;
  retryable: boolean;
};

export type EventPage = {
  has_more: boolean;
  items: Array<ProjectionEvent>;
  kind: "event-page";
  oldest_cursor: Cursor;
  resume_cursor: Cursor;
};

export type Fence = {
  attempt?: number;
  mission_generation?: RunGenerationId;
  preview_token?: string;
  readiness_epoch?: number;
  runtime_desired_revision?: string;
  runtime_incarnation?: string;
  snapshot_id: SnapshotId;
  step_definition?: Revision;
  subject_revisions: {
  [key: string]: Revision;
};
  terminal_sequence?: number;
};

export type Glass = ResourceHeader & {
  base_revision: string | null;
  body: (GlassBody | null);
  deleted: boolean;
  kind: "glass";
  replaced_revision: string | null;
};

export type GlassBody = {
  layout: GlassLayout;
  name: string;
};

export type GlassDelete = {
  base_revision: string | null;
};

export type GlassLayout = ({
  tabs: Array<GlassTab>;
} | {
  children: Array<GlassLayout>;
  ratio?: number;
  split: "right" | "below";
});

export type GlassPut = {
  base_revision: string | null;
  body: GlassBody;
};

export type GlassTab = {
  pane: string;
  title?: string;
};

export type GoldenResourceSet = Array<Resource>;

export type HarnessPhase = {
  name: string;
  tasks: Array<HarnessTask>;
};

export type HarnessTask = {
  blocker?: string | null;
  content: string;
  status: "pending" | "in_progress" | "completed" | "blocked";
};

export type HarnessTodoSnapshot = {
  harness: string;
  incarnation_id: string;
  observed_at: Timestamp;
  phases: Array<HarnessPhase>;
  session_id: string;
  source_op: string;
  totals: HarnessTodoTotals;
  truncated: boolean;
};

export type HarnessTodoTotals = {
  abandoned?: number;
  blocked: number;
  completed: number;
  in_progress: number;
  pending: number;
};

export type History = ResourceHeader & {
  event_type: string;
  kind: "history";
  occurred_at: Timestamp;
  store_index: number;
  summary: string;
  targets: Array<Id>;
};

export type HostId = string;

export type HostRepositories = {
  host_id: string;
  repositories: Array<AgentRepository>;
};

export type Id = string;

export type Lane = ResourceHeader & {
  approver_id: (Id | null);
  entries: Array<LaneEntry>;
  entries_prefix: string | null;
  kind: "lane";
  mission_id: (Id | null);
  mission_run_id: (Id | null);
  name: string;
  recent: Array<LaneChange>;
  state: "open" | "closed";
};

export type LaneChange = {
  actor_id: Id;
  anchor_id: (Id | null);
  at: Timestamp;
  change: "joined" | "left" | "moved" | "approved";
  entry_id: Id;
  label: string;
  outcome: ("completed" | "removed" | null);
  placement: ("top" | "bottom" | "before" | "after" | null);
  reason: string | null;
};

export type LaneEntry = {
  approved_at: (Timestamp | null);
  approved_by_id: (Id | null);
  detail: string | null;
  entry_id: Id;
  head: string | null;
  join_reason: string | null;
  joined_at: Timestamp;
  joined_by_id: Id;
  label: string;
  marked_at: (Timestamp | null);
  marked_by_id: (Id | null);
  position: number;
  state: "waiting" | "held" | "ready" | "running";
};

export type Launch = ResourceHeader & {
  approvals: Array<Id>;
  decisions: Array<Id>;
  kind: "launch";
  phase: "authoring" | "review" | "approved" | "cancelled" | "failed";
  planner: Id;
  planner_config: PlannerConfig;
  preview?: (LaunchPreview | null);
  preview_token?: string | null;
  request: string;
  target: {
  generation_id?: Id;
  mission_id?: Id;
  mission_run_id?: Id;
  type: "new-mission" | "mission-run";
  workspace?: string;
};
  title: string;
  variants: Array<Id>;
  visualization?: Visualization;
};

export type LaunchApproval = ResourceHeader & {
  decided_at: Timestamp;
  kind: "launch-approval";
  launch_id: Id;
  preview_token: string;
  reviewer: Id;
  state: "approved" | "rejected";
  variant_id: Id;
};

export type LaunchDecision = ResourceHeader & {
  decision_type: "boolean" | "single-choice" | "multiple-choice" | "rank";
  explanation?: string | null;
  kind: "launch-decision";
  launch_id: Id;
  options: Array<DecisionOption>;
  question: string;
  requested_at: Timestamp;
  response?: (DecisionResponse | null);
  state: "open" | "answered" | "withdrawn";
};

export type LaunchPreview = {
  agents: Array<{
  harness?: unknown;
  host?: string | null;
  id: string;
  worktree?: string | null;
}>;
  diagnostics_count: number;
  gates: {
  automated: number;
  human: number;
};
  goal: string;
  request_excerpt: string;
  steps: Array<{
  assignee?: string | null;
  depends: Array<string>;
  path: string;
  title: string;
}>;
};

export type LaunchVariant = ResourceHeader & {
  candidate_revision: number;
  diagnostics: Array<Diagnostic>;
  kind: "launch-variant";
  launch_id: Id;
  normalized_mission: {

};
  ordinal: number;
  preview_token?: string | null;
  status: "draft" | "previewable" | "blocked" | "approved" | "rejected";
  structured_diff?: StructuredDiff;
  target_generation?: (Id | null);
  visualization?: Visualization;
};

export type Machine = ResourceHeader & {
  capacity: MachineCapacity;
  fleet_id?: string | null;
  host_id: Id;
  kind: "machine";
  name: string;
  occupancy: MachineOccupancy;
  projects: Array<string>;
  runtime_ids: Array<Id>;
  state: "local" | "reachable" | "unreachable" | "indeterminate" | "dial-out";
  transports: Array<MachineTransport>;
  work: Array<Id>;
};

export type MachineCapacity = {
  reason: string;
  state: "reported" | "unknown";
};

export type MachineOccupancy = {
  running_runtimes: number;
};

export type MachineTransport = {
  last_success_at?: (Timestamp | null);
  protocol: string;
  status: "local" | "up" | "down" | "unknown";
};

export type Message = ResourceHeader & {
  attachments?: Array<Attachment>;
  content: string;
  from: Id;
  in_reply_to?: (Id | null);
  kind: "message";
  sent_at: Timestamp;
  session_id?: (Id | null);
  state: "sent" | "delivered" | "read" | "closed";
  tags?: Array<string>;
  title?: string | null;
  to: Id;
};

export type Mission = ResourceHeader & {
  active_runs?: number;
  id?: MissionId;
  kind: "mission";
  mission_revision: Revision;
  must_act?: MustAct;
  run_counts?: {
  [key: string]: number;
};
  run_details?: Array<MissionRunSummary>;
  run_generations: {
  [key: string]: RunGenerationId;
};
  runs: Array<MissionRunId>;
  runs_truncated?: boolean;
  state: MissionState;
  title: string;
  total_runs?: number;
  usage?: (UsageSummary | null);
  visualization?: (Visualization | null);
};

export type MissionId = string;

export type MissionRunId = string;

export type MissionRunOutcome = {
  actor: ActorRef;
  at: Timestamp;
  previous_status?: string | null;
  reason: string;
  status: RunOutcomeStatus;
};

export type MissionRunSummary = {
  after?: (Id | null);
  blocker?: {

} | null;
  current_steps: Array<{
  assignee?: (AgentId | null);
  claimant?: (AgentId | null);
  id: StepRunId;
  since: Timestamp;
  state: WorkState;
  title: string | null;
}>;
  deadline?: (Timestamp | null);
  generation_id?: RunGenerationId;
  id: MissionRunId;
  last_progress?: string | null;
  must_act: MustAct;
  outcome?: (MissionRunOutcome | null);
  phase: string;
  progress: {
  done: number;
  total: number;
};
  requester: ActorRef;
  state_since: Timestamp;
  status: string;
  steps?: (Array<MissionStep> | null);
};

export type MissionState = ("draft" | "ready" | "retired" | "running" | "standing" | "completed" | "failed" | "cancelled" | string);

export type MissionStep = {
  agentless?: boolean;
  assignee?: (AgentId | null);
  attempt: number;
  blocked_reason?: string | null;
  blockers?: Array<Id>;
  claimant?: (AgentId | null);
  constraints?: Array<string>;
  goals?: Array<string>;
  id: Id;
  last_progress?: string | null;
  path: string;
  since: Timestamp;
  state: WorkState;
  title?: string | null;
};

export type MustAct = ("you" | "agent" | "system" | "blocked" | "nobody" | string);

export type Observer = ResourceHeader & {
  kind: "observer";
  owner_generation_id: string | null;
  owner_run_id: string | null;
  owner_step_id: string | null;
  spec: ObserverSpec;
  state: string;
};

export type ObserverSpec = {
  fields: Array<string>;
  locator: string;
  provider: string;
  resource: string;
  stopped: boolean;
};

export type Operation = ResourceHeader & {
  component: "daemon" | "host" | "transport" | "observer" | "runtime" | "action";
  kind: "operation";
  severity: "critical" | "warning" | "info";
  state: "pending" | "running" | "healthy" | "degraded" | "failed" | "completed";
  summary: string;
  targets?: Array<Id>;
};

export type Operational = {
  actionable: boolean;
  layer: "current" | "history";
  owner_generation?: string | null;
  reasons?: Array<string>;
  runtime_incarnation?: string | null;
};

export type OwnedSet = ResourceHeader & {
  blockers: Array<string>;
  claim: string;
  commit_status?: {

} | null;
  kind: "owned-set";
  members_status: Array<{

}>;
  receipt: {

};
  visibility: {

};
};

export type Page = {
  collection: string;
  filters: {
  [key: string]: string;
};
  items: Array<Resource>;
  kind: "page";
  page: PageInfo;
  replicated?: ReplicatedNotice;
  sync?: SyncNotice;
};

export type PageInfo = {
  cursor_expires_at?: (Timestamp | null);
  has_more: boolean;
  limit: number;
  next_cursor?: string | null;
};

export type PairedSession = {
  credential: string;
  device_id: Id;
  device_key_chain?: Array<string>;
  expires_at: Timestamp;
  kind: "paired-session";
  person_id: string;
  scopes: Array<string>;
  session_actor: Id;
};

export type PairingBegin = {
  api_version: "st3.client.v0";
  device_name: string;
  full_control?: boolean;
  person_id: string;
};

export type PairingChallenge = {
  code: string;
  expires_at: Timestamp;
  kind: "pairing-challenge";
  pairing_id: Id;
};

export type PairingComplete = {
  api_version: "st3.client.v0";
  code: string;
  device_public_key: string;
  key_storage?: "secure-enclave" | "software";
};

export type ParticipantRef = string;

export type PersonAnswer = {
  id?: string;
  label?: string;
  outcome: "accept" | "decline" | "request_changes" | "selected" | "custom" | "feedback" | "read";
  text?: string;
  type: "decision" | "choice" | "feedback" | "update";
};

export type PersonAnswerInput = {
  id?: string;
  text?: string;
};

export type PersonAnswerRecord = {
  answer?: PersonAnswer;
  answered_at_unix_ms: number;
  ask: Id;
  evidence?: Array<Id>;
  respondent: Id;
  status: "completed" | "cancelled";
  summary: string;
};

export type PersonAskParameters = {
  new_run?: string;
  person_id: Id;
  reason: string;
  request?: StructuredRequest;
  step_id?: Id;
  title: string;
};

export type PersonStepParameters = {
  answer?: PersonAnswerInput;
  episode: string;
  evidence?: Array<Id>;
  summary: string;
  target_id: Id;
};

export type PersonUpdate = {
  about: Id;
  subjects?: Array<RequestSubject>;
  summary?: string;
  type: "update";
  version: 1;
};

export type PlannerConfig = {
  effort?: string;
  model?: string;
  provider: "codex" | "claude" | "pi" | "omp" | "opencode";
};

export type ProjectionEvent = Omit<{
  body: {

};
  epoch: string;
  id: Id;
  next_cursor: Cursor;
  previous_cursor: Cursor;
  resource_ids: Array<Id>;
  sequence: number;
  snapshot_id: Id;
  timestamp: Timestamp;
  type: "upsert" | "delete" | "timeline.delta" | "terminal.available" | "capabilities.changed";
}, 'type' | 'body'> & ({ type: "timeline.delta"; body: TimelineDelta });

export type ReplicatedNotice = {
  complete: boolean;
  owner_host_id: Id;
  reason?: string;
  source: "owner" | "replica";
  state: "current" | "lagging" | "unverified";
};

export type RequestAnswerOption = {
  conditions?: Array<string>;
  consequence: string;
  id: string;
  label: string;
  outcome?: "accept" | "decline" | "request_changes";
};

export type RequestId = string;

export type RequestSubject = {
  kind: "pull_request" | "issue" | "document" | "mission" | "run" | "step" | "agent" | "host" | "commit" | "link";
  label: string;
  ref?: string;
  revision?: string;
  url?: string;
};

export type Resource = (Attention | Message | Launch | LaunchVariant | LaunchDecision | LaunchApproval | Mission | Work | Agent | Runtime | Observer | Subscription | Lane | Machine | Device | Operation | History | Session | Glass | Arrangement | OwnedSet);

export type ResourceHeader = {
  id: Id;
  kind: ("attention" | "message" | "launch" | "launch-variant" | "launch-decision" | "launch-approval" | "mission" | "work" | "agent" | "runtime" | "observer" | "subscription" | "lane" | "machine" | "device" | "operation" | "history" | "session" | "glass" | "arrangement" | string);
  operational?: Operational;
  revision: Revision;
  updated_at: Timestamp;
};

export type ResourceObservation = {
  facts: {

};
  id: Id;
  kind: string;
  observed_at: Timestamp;
  opened_by: string | null;
  opened_by_run: string | null;
};

export type ResourcesFilter = {
  kind?: string;
  opened_by?: string;
  subject_prefix?: string;
};

export type ResourcesPage = {
  collection: "resources";
  filters: {
  [key: string]: string;
};
  items: Array<ResourceObservation>;
  kind: "page";
  page: PageInfo;
  sync?: SyncNotice;
};

export type Revision = string;

export type RunGenerationId = string;

export type RunOutcomeStatus = ("completed" | "failed" | "cancelled" | string);

export type Runtime = ResourceHeader & {
  desired_revision: (Revision | null);
  incarnation_id: string | null;
  kind: "runtime";
  owner_host_id: Id;
  owner_id: Id;
  owner_run_id?: (Id | null);
  runtime_id: string;
  runtime_kind: "agent" | "exec" | "terminal" | "observer" | "gate";
  state: "pending" | "starting" | "running" | "stopping" | "stopped" | "exited" | "failed" | "unreachable";
  terminal_access?: {

} | null;
  terminal_id?: (Id | null);
  terminal_sequence?: number | null;
};

export type RuntimeId = string;

export type Session = ResourceHeader & {
  ended_at?: (Timestamp | null);
  kind: "session";
  owner_id: Id;
  runtime_incarnation?: string | null;
  started_at: Timestamp;
  state: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled";
  timeline_cursor: Cursor;
  usage?: (UsageSummary | null);
};

export type Snapshot = {
  created_at: Timestamp;
  host_id: HostId;
  id: SnapshotId;
  projection_version: "client-projection.v0";
  store_index: number;
};

export type SnapshotId = string;

export type StepRunId = string;

export type StructuredDiff = {
  changes: Array<{

}>;
  predicted_actions: Array<{

}>;
};

export type StructuredRequest = {
  answers?: Array<RequestAnswerOption>;
  custom?: boolean;
  question: string;
  reasons?: Array<string>;
  recommendation?: {
  answer: string;
  reason: string;
};
  subjects?: Array<RequestSubject>;
  summary?: string;
  type: "decision" | "choice" | "feedback";
  version: 1;
  why_person: string;
};

export type SubjectDefinition = {
  conflicts: Array<string>;
  desired: CanonicalNode;
  desired_revision: Revision;
  desired_token: string;
  kdl: string;
  kind: "subject-definition";
  subject: string;
};

export type Subscription = ResourceHeader & {
  kind: "subscription";
  owner_generation_id: string | null;
  owner_run_id: string | null;
  owner_step_id: string | null;
  spec: SubscriptionSpec;
  state: string;
};

export type SubscriptionSpec = {
  condition?: {

} | null;
  delivery: string;
  fields: Array<string>;
  mission?: string | null;
  observer: string;
  requester?: string | null;
  resource_input?: string | null;
  revision?: string | null;
  stopped: boolean;
  to: string;
  workspace?: string | null;
};

export type SyncNotice = {
  peers: Array<SyncPeer>;
  state: "catching-up" | "diverged";
};

export type SyncPeer = {
  diverged_since?: (Timestamp | null);
  estimated_catch_up_seconds?: number | null;
  host_id: Id;
  last_exchange_at?: (Timestamp | null);
  local_only_envelopes: number;
  peer_only_envelopes: number;
};

export type TargetParameters = {
  evidence?: Array<Id>;
  reason?: string;
  summary?: string;
  target_id: Id;
};

export type TerminalAttachment = {
  attachment_id: Id;
  expires_at: Timestamp;
  owner_host_id: Id;
  retry_hint?: "reattach" | null;
  reusable?: boolean;
  runtime_incarnation: string;
  state: "available" | "consumed" | "detached" | "expired";
  stream_capability: string | null;
  stream_url: string;
  terminal_id: Id;
  ttl_s?: number;
};

export type TerminalColor = (number | string);

export type TerminalCreateParameters = {
  cwd?: string;
  host?: string;
  name: string;
};

export type TerminalFacts = {
  clients?: {
  attached: number;
  read_only: number;
  total: number;
};
  columns?: number;
  process?: {
  alive: boolean;
  exit_code?: number;
};
  rows?: number;
  tags?: {
  [key: string]: string;
};
  uptime_s?: number;
};

export type TerminalId = string;

export type TerminalLine = {
  redacted: boolean;
  row: number;
  runs: Array<TerminalRun>;
  text: string;
  truncated: boolean;
  wrapped?: boolean;
};

export type TerminalLink = {
  uri: string;
};

export type TerminalModes = {
  alternate_screen: boolean;
  application_cursor: boolean;
  application_keypad: boolean;
  bracketed_paste: boolean;
  focus_events: boolean;
  kitty_keyboard?: number;
  mouse_encoding: "default" | "utf8" | "sgr";
  mouse_tracking: "none" | "click" | "drag" | "motion";
};

export type TerminalRelay = {
  capability_ttl_s: number;
  direct: boolean;
  fence_conflicts: number;
  owner_host_id: Id;
  rtt_ms: number;
  transport: "fabric" | "http";
  via: Id;
};

export type TerminalRun = {
  bg?: TerminalColor;
  bold?: true;
  cells?: number;
  dim?: true;
  fg?: TerminalColor;
  inverse?: true;
  italic?: true;
  link?: TerminalLink;
  strikethrough?: true;
  text: string;
  underline?: true;
};

export type TerminalScreen = {
  columns: number;
  cursor: {
  blinking: boolean;
  column: number;
  row: number;
  style: "block" | "underline" | "bar";
  visible: boolean;
};
  facts?: TerminalFacts;
  kind: "terminal-screen";
  lines: Array<TerminalLine>;
  modes: TerminalModes;
  next_sequence: number;
  relay?: TerminalRelay;
  revision: string;
  rows: number;
  runtime_incarnation: string;
  terminal_id: TerminalId;
  title: string;
  truncated: boolean;
};

export type TimelineContentBody = (unknown | unknown);

export type TimelineDelta = {
  entry?: TimelineEntry;
  entry_id: Id;
  operation: "append" | "replace" | "finalize";
  revision: number;
};

export type TimelineEntry = Omit<{
  body: {

};
  final: boolean;
  id: TimelineEntryId;
  revision: number;
  role: "system" | "user" | "assistant" | "tool";
  sequence: number;
  timestamp: Timestamp;
  type: ("message" | "content" | "tool_call" | "tool_result" | "status" | "error" | "usage" | "redaction" | "truncation" | string);
}, 'type' | 'body'> & ({ type: "message"; body: TimelineMessageBody } | { type: "content"; body: TimelineContentBody } | { type: "tool_call"; body: TimelineToolCallBody } | { type: "tool_result"; body: TimelineToolResultBody } | { type: "status"; body: TimelineStatusBody } | { type: "error"; body: TimelineErrorBody } | { type: "usage"; body: TimelineUsageBody } | { type: "redaction"; body: TimelineRedactionBody } | { type: "truncation"; body: TimelineTruncationBody });

export type TimelineEntryId = string;

export type TimelineErrorBody = {
  code: string;
  details: {

};
  message: string;
  retryable: boolean;
};

export type TimelineMessageBody = {
  attachments?: Array<Attachment>;
  from?: ParticipantRef;
  message_id: string;
  reply_to?: string | null;
  tags?: Array<string>;
  title?: string;
  to?: ParticipantRef;
};

export type TimelinePage = {
  items: Array<TimelineEntry>;
  kind: "timeline-page";
  page: PageInfo;
  session_id: Id;
};

export type TimelineRedactionBody = {
  reason: string;
  withheld_bytes: number;
  withheld_items?: number;
};

export type TimelineStatus = ("queued" | "running" | "waiting" | "completed" | "failed" | "cancelled" | string);

export type TimelineStatusBody = {
  detail?: string;
  status: TimelineStatus;
};

export type TimelineToolCallBody = {
  arguments: unknown;
  call_id: string;
  name: string;
};

export type TimelineToolResultBody = {
  call_id: string;
  content: unknown;
  media_type: string;
  status: "success" | "error";
};

export type TimelineTruncationBody = {
  continuation_cursor?: Cursor;
  omitted_from_sequence: number;
  omitted_to_sequence: number;
  reason: string;
};

export type TimelineUsageBody = {
  attribution: {
  agent_id: Id;
  generation_id?: string | null;
  mission_run_id?: string | null;
  step_id?: string | null;
};
  cache_write_tokens?: number;
  cached_tokens?: number;
  compactions?: number;
  context_used_percent?: number;
  context_used_tokens?: number;
  context_window_tokens?: number;
  cost?: number;
  currency?: string;
  driver: string;
  input_tokens?: number;
  last_compaction_ms?: number;
  last_compaction_trigger?: "manual" | "auto" | "threshold" | "overflow" | "idle" | "unknown";
  model?: string;
  output_tokens?: number;
  semantics: "context_occupancy" | "session_cumulative" | "response";
  total_tokens?: number;
  turn_id?: string;
};

export type Timestamp = string;

export type UnknownResource = ResourceHeader & {
  kind?: string;
};

export type UsageContext = {
  compactions?: number;
  last_compaction_ms?: number;
  last_compaction_trigger?: "manual" | "auto" | "threshold" | "overflow" | "idle" | "unknown";
  model?: string;
  observed_at_unix_ms: number;
  used_percent?: number;
  used_tokens?: number;
  window_tokens?: number;
};

export type UsageLimit = {
  account: string;
  account_ref?: string;
  driver: string;
  five_hour_percent?: number;
  five_hour_resets_at_unix_ms?: number;
  host: string;
  measured_at_unix_ms: number;
  measured_by: string;
  plan?: string;
  seats: Array<string>;
  weekly_percent?: number;
  weekly_resets_at_unix_ms?: number;
};

export type UsagePeriod = {
  limits?: Array<UsageLimit>;
  rows: Array<UsageRow>;
  since_ms: number;
  until_ms: number;
};

export type UsageRow = {
  account?: string;
  agent: Id;
  cache_write_1h_tokens: number;
  cache_write_tokens: number;
  cached_tokens: number;
  cost_microusd: number;
  host?: string;
  input_tokens: number;
  mission_run?: Id;
  model?: string;
  output_tokens: number;
  pricing?: string;
  reported_cost_microusd: number;
  step?: Id;
  total_tokens: number;
  unpriced_tokens: number;
};

export type UsageSummary = {
  aggregation: "cumulative-per-incarnation-else-response-deltas";
  cache_write_tokens?: number;
  cached_tokens: number;
  context?: UsageContext;
  cost?: number;
  currency?: string;
  incarnation_count: number;
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
};

export type Visualization = {
  constraints: Array<string>;
  decisions: Array<LaunchDecision>;
  diffs: Array<StructuredDiff>;
  edges: Array<VisualizationEdge>;
  gates: Array<{

}>;
  goals: Array<string>;
  groups: Array<VisualizationGroup>;
  live_progress: {

};
  mission?: string;
  nodes: Array<VisualizationNode>;
  resources: Array<{

}>;
  revision: {

};
  risk: {

};
  swimlanes: Array<{
  assignment: string;
  id: string;
  nodes: Array<string>;
}>;
  timeline: {
  entries: Array<{

}>;
};
  version: "st3.visualization.v0";
  views: Array<"graph" | "timeline" | "swimlane" | "revision" | "risk" | "live-progress">;
};

export type VisualizationEdge = {
  from: string | null;
  gate: unknown;
  id: string;
  kind: "dependency" | "gate";
  to: string;
};

export type VisualizationGroup = {
  id: string;
  kind: "queue" | "nested-mission";
  members: Array<string>;
};

export type VisualizationNode = {
  assignment?: unknown;
  constraints: Array<string>;
  gates?: Array<unknown>;
  goals: Array<string>;
  id: string;
  kind: string;
  label: string;
  loop?: unknown;
  path: string;
  resources?: Array<unknown>;
  retry?: {

};
  runtime: {

};
  source_references?: Array<unknown>;
  timeout_ms?: number | null;
};

export type Work = ResourceHeader & {
  agentless?: boolean;
  assigned_to?: (Id | null);
  attempt: number;
  blocked_reason?: string | null;
  blockers?: Array<Id>;
  claim_expires_at_unix_ms?: number | null;
  claim_incarnation?: string | null;
  claimant?: (Id | null);
  constraints: Array<string>;
  definition_id: Revision;
  execution_elapsed_ms?: number;
  execution_started_at_unix_ms?: number | null;
  gate_kind?: "watch" | "predicate" | "command" | "llm" | "human" | "mixed" | "run" | null;
  generation_id: Id;
  goals: Array<string>;
  kind: "work";
  last_progress?: string | null;
  mission_id?: (Id | null);
  mission_run_id: Id;
  path: string;
  person_answers?: Array<PersonAnswerRecord>;
  readiness_epoch: number;
  state: WorkState;
  timeout_ms?: number | null;
  title?: string | null;
  usage?: (UsageSummary | null);
};

export type WorkLabel = {
  goal?: string | null;
  id: Id;
  mission_id: MissionId;
  mission_run_id: MissionRunId;
  path: string;
  since: Timestamp;
  state: WorkState;
  title?: string | null;
};

export type WorkState = "waiting-person" | "waiting" | "ready" | "claimed" | "blocked" | "verifying" | "completed" | "failed" | "cancelled";

export type ActionRequest =
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'agent.create'; parameters: AgentCreateParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'agent.queue-move'; parameters: {
  agent_id: Id;
  anchor_run_id?: Id;
  mission_run_id: Id;
  placement: "top" | "bottom" | "before" | "after";
  reason?: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'agent.resume'; parameters: AgentResumeParameters; fence: Fence & Required<Pick<Fence, 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'agent.start'; parameters: AgentStartParameters; fence: Fence & Required<Pick<Fence, 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'agent.stop'; parameters: AgentStopParameters; fence: Fence & Required<Pick<Fence, 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'agent.suspend'; parameters: AgentSuspendParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'arrangement.edit'; parameters: ArrangementEditParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'attention.resolve'; parameters: {
  attention_id: Id;
  outcome: string;
  reason?: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'lane.approve'; parameters: {
  anchor_id?: Id;
  detail?: string;
  entry_id: Id;
  head?: string;
  lane_id: Id;
  outcome?: "completed" | "removed";
  placement?: "top" | "bottom" | "before" | "after";
  reason?: string;
  state?: "waiting" | "held" | "ready" | "running";
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'lane.join'; parameters: {
  anchor_id?: Id;
  detail?: string;
  entry_id: Id;
  head?: string;
  lane_id: Id;
  outcome?: "completed" | "removed";
  placement?: "top" | "bottom" | "before" | "after";
  reason?: string;
  state?: "waiting" | "held" | "ready" | "running";
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'lane.leave'; parameters: {
  anchor_id?: Id;
  detail?: string;
  entry_id: Id;
  head?: string;
  lane_id: Id;
  outcome?: "completed" | "removed";
  placement?: "top" | "bottom" | "before" | "after";
  reason?: string;
  state?: "waiting" | "held" | "ready" | "running";
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'lane.mark'; parameters: {
  anchor_id?: Id;
  detail?: string;
  entry_id: Id;
  head?: string;
  lane_id: Id;
  outcome?: "completed" | "removed";
  placement?: "top" | "bottom" | "before" | "after";
  reason?: string;
  state?: "waiting" | "held" | "ready" | "running";
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'lane.move'; parameters: {
  anchor_id?: Id;
  detail?: string;
  entry_id: Id;
  head?: string;
  lane_id: Id;
  outcome?: "completed" | "removed";
  placement?: "top" | "bottom" | "before" | "after";
  reason?: string;
  state?: "waiting" | "held" | "ready" | "running";
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.approve'; parameters: {
  launch_id: Id;
  variant_id: Id;
}; fence: Fence & Required<Pick<Fence, 'preview_token'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.cancel'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.create'; parameters: {
  effort?: string;
  model?: string;
  provider?: "codex" | "claude" | "pi" | "omp" | "opencode";
  request: string;
  target: ({
  mission_id: Id;
  type: "new-mission";
  workspace: string;
} | {
  generation_id: Id;
  mission_run_id: Id;
  type: "mission-run";
});
  title: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.preview'; parameters: {
  launch_id: Id;
  variant_id: Id;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.revise'; parameters: {
  feedback: string;
  launch_id: Id;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'message.close'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'message.read'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'message.send'; parameters: {
  attachments?: Array<AttachmentInput>;
  content: string;
  in_reply_to?: Id;
  session_id?: Id;
  signature?: DeviceSignature;
  tags?: Array<string>;
  title?: string;
  to: Id;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.approve-revision'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'preview_token' | 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.cancel'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.cancel-revision'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.revise'; parameters: {
  launch_id: Id;
  mission_run_id: Id;
}; fence: Fence & Required<Pick<Fence, 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.start'; parameters: {
  inputs: {
  [key: string]: string;
};
  mission_id: Id;
  workspace: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'pairing.revoke'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'review.approve'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'review.reject'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'review.request-changes'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.context-clear'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.reset'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.restart'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.signal'; parameters: {
  signal: "interrupt" | "terminate" | "kill";
  target_id: Id;
}; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.stop'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'runtime_desired_revision'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'session.import'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'subject_revisions'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.attach'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.create'; parameters: TerminalCreateParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.detach'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.end'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.input'; parameters: {
  mode: "line" | "raw" | "key";
  terminal_id: Id;
  value: string;
}; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'terminal_sequence'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.resize'; parameters: {
  columns: number;
  rows: number;
  terminal_id: Id;
}; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'terminal_sequence'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.ask'; parameters: PersonAskParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.cancel-ask'; parameters: PersonStepParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.claim'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.complete'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.done'; parameters: PersonStepParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.fail'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.progress'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.publish-mission'; parameters: {
  mission: {

};
  name: string;
  target_id: Id;
}; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch' | 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.release'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.renew'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.retry'; parameters: {
  reason: string;
  target_id: Id;
}; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> });
export type ActionOf<T extends ActionRequest['type']> = Extract<ActionRequest, { type: T }>;
export type EnvelopeOf<T> = Omit<Envelope, 'value'> & { value: T };
