// @generated by st3-client-codegen; contract sha256 acd964b4fa85c67b2f44507b1fc39a95a153ad65bfc69731762f458b5dd5d6ab
// Source: docs/st3/client-v0/schemas/client-v0.schema.json

export const CONTRACT_SHA256 = 'acd964b4fa85c67b2f44507b1fc39a95a153ad65bfc69731762f458b5dd5d6ab' as const;
export const API_VERSION = 'st3.client.v0' as const;

export type ActionCommon = {
  api_version: "st3.client.v0";
  fence: Fence;
  id: Id;
  idempotency_key: string;
  parameters: {

};
  type: "attention.resolve" | "review.approve" | "review.reject" | "message.send" | "message.read" | "message.close" | "launch.create" | "launch.revise" | "launch.preview" | "launch.approve" | "launch.cancel" | "mission.start" | "mission.revise" | "mission.approve-revision" | "mission.cancel-revision" | "mission.cancel" | "session.import" | "work.claim" | "work.renew" | "work.progress" | "work.complete" | "work.fail" | "work.release" | "work.publish-mission" | "runtime.stop" | "runtime.restart" | "runtime.reset" | "runtime.context-clear" | "runtime.signal" | "terminal.input" | "terminal.resize" | "terminal.attach" | "terminal.detach" | "pairing.revoke";
};

export type ActionResult = {
  action_id: Id;
  affected_ids: Array<Id>;
  kind: "action-result";
  operation_id: Id;
  snapshot_id: Id;
  status: "accepted" | "completed" | "rejected";
  terminal_attachment?: (TerminalAttachment | null);
};

export type Agent = ResourceHeader & {
  active_work_count?: number;
  current_session_id?: string | null;
  current_work_ids?: Array<Id>;
  driver?: string | null;
  harness_state?: string | null;
  incarnation_id?: string | null;
  kind: "agent";
  name: string;
  next_work_id?: (Id | null);
  owner_run_id?: (Id | null);
  queued_work_count?: number;
  reachability: "local" | "remote" | "unreachable" | "unknown";
  runtime_ids: Array<Id>;
  state: "desired" | "starting" | "running" | "waiting" | "stopped" | "failed";
  under?: Array<AgentRelationship>;
  upcoming_work_ids?: Array<Id>;
};

export type AgentRelationship = {
  agent_id: Id;
  reason?: string | null;
};

export type Attention = ResourceHeader & {
  actions: Array<"attention.resolve" | "review.approve" | "review.reject" | "launch.approve" | "launch.cancel" | "mission.approve-revision" | "mission.cancel-revision" | "message.read">;
  attention_kind: "human-gate" | "launch-approval" | "revision-approval" | "unread-message" | "fault";
  detail: string;
  kind: "attention";
  mission_id?: Id;
  mission_run_id?: Id;
  person_id: Id;
  priority: "critical" | "high" | "normal" | "low";
  requested_at: Timestamp;
  source_id: Id;
  state: "open" | "resolved";
  step_run_id?: Id;
  targets?: Array<Id>;
  title: string;
};

export type Capabilities = {
  capabilities: Array<Capability>;
  event_cursor: Cursor;
  kind: "capabilities";
  limits: {
  max_event_items: number;
  max_page_items: number;
  max_response_bytes: number;
  max_wait_ms: number;
};
  oldest_event_cursor: Cursor;
  schemas: Array<string>;
  session_actor: Id;
  transport: "unix" | "fabric-loopback";
};

export type Capability = {
  id: string;
  state: "granted" | "ungranted" | "unavailable" | "unsupported";
  version: number;
};

export type Cursor = string;

export type DecisionOption = {
  description?: string | null;
  id: string;
  label: string;
};

export type DecisionResponse = ({
  type: "boolean";
  value: boolean;
} | {
  type: "single-choice";
  value: string;
} | {
  type: "multiple-choice";
  value: Array<string>;
} | {
  type: "rank";
  value: Array<string>;
});

export type Device = ResourceHeader & {
  expires_at: Timestamp;
  kind: "device";
  person_id: Id;
  scopes: Array<string>;
  session_actor: Id;
  state: "active" | "expired" | "revoked";
};

export type Diagnostic = {
  code: string;
  message: string;
  path?: string | null;
  severity: "info" | "warning" | "error";
};

export type Envelope = {
  api_version: "st3.client.v0";
  request_id: Id;
  snapshot: Snapshot;
  value: (Capabilities | Page | Resource | TimelinePage | EventPage | ActionResult | PairingChallenge | PairedSession | TerminalScreen | TerminalFramePage);
};

export type ErrorEnvelope = {
  api_version: "st3.client.v0";
  code: "not-found" | "forbidden" | "unsupported-capability" | "validation-failed" | "idempotency-conflict" | "stale-fence" | "cursor-gap" | "page-cursor-expired" | "rate-limited" | "runtime-not-local" | "runtime-authority-indeterminate" | "remote-unavailable" | "internal";
  details: {

};
  error_version: "st3.client.error.v0";
  message: string;
  request_id: Id;
  retry_after_ms?: number;
  retryable: boolean;
};

export type EventPage = {
  has_more: boolean;
  items: Array<ProjectionEvent>;
  kind: "event-page";
  oldest_cursor: Cursor;
  resume_cursor: Cursor;
};

export type Fence = {
  attempt?: number;
  mission_generation?: Id;
  preview_token?: string;
  readiness_epoch?: number;
  runtime_incarnation?: string;
  snapshot_id: Id;
  step_definition?: Revision;
  subject_revisions: {
  [key: string]: Revision;
};
  terminal_sequence?: number;
};

export type GoldenResourceSet = Array<Resource>;

export type History = ResourceHeader & {
  event_type: string;
  kind: "history";
  occurred_at: Timestamp;
  store_index: number;
  summary: string;
  targets: Array<Id>;
};

export type Id = string;

export type Launch = ResourceHeader & {
  approvals: Array<Id>;
  decisions: Array<Id>;
  kind: "launch";
  phase: "authoring" | "review" | "approved" | "cancelled" | "failed";
  planner: Id;
  planner_config: PlannerConfig;
  request: string;
  target: {
  generation_id?: Id;
  mission_id?: Id;
  mission_run_id?: Id;
  type: "new-mission" | "mission-run";
  workspace?: string;
};
  title: string;
  variants: Array<Id>;
  visualization?: Visualization;
};

export type LaunchApproval = ResourceHeader & {
  decided_at: Timestamp;
  kind: "launch-approval";
  launch_id: Id;
  preview_token: string;
  reviewer: Id;
  state: "approved" | "rejected";
  variant_id: Id;
};

export type LaunchDecision = ResourceHeader & {
  decision_type: "boolean" | "single-choice" | "multiple-choice" | "rank";
  explanation?: string | null;
  kind: "launch-decision";
  launch_id: Id;
  options: Array<DecisionOption>;
  question: string;
  requested_at: Timestamp;
  response?: (DecisionResponse | null);
  state: "open" | "answered" | "withdrawn";
};

export type LaunchVariant = ResourceHeader & {
  candidate_revision: number;
  diagnostics: Array<Diagnostic>;
  kind: "launch-variant";
  launch_id: Id;
  normalized_mission: {

};
  ordinal: number;
  preview_token?: string | null;
  status: "draft" | "previewable" | "blocked" | "approved" | "rejected";
  structured_diff?: StructuredDiff;
  target_generation?: (Id | null);
  visualization?: Visualization;
};

export type Machine = ResourceHeader & {
  capacity: MachineCapacity;
  fleet_id?: string | null;
  host_id: Id;
  kind: "machine";
  name: string;
  occupancy: MachineOccupancy;
  projects: Array<string>;
  runtime_ids: Array<Id>;
  state: "local" | "reachable" | "unreachable" | "indeterminate";
  transports: Array<MachineTransport>;
  work: Array<Id>;
};

export type MachineCapacity = {
  reason: string;
  state: "reported" | "unknown";
};

export type MachineOccupancy = {
  running_runtimes: number;
};

export type MachineTransport = {
  last_success_at?: (Timestamp | null);
  protocol: string;
  status: "local" | "up" | "down" | "unknown";
};

export type Message = ResourceHeader & {
  content: string;
  from: Id;
  in_reply_to?: (Id | null);
  kind: "message";
  sent_at: Timestamp;
  session_id?: (Id | null);
  state: "sent" | "delivered" | "read" | "closed";
  tags?: Array<string>;
  title?: string | null;
  to: Id;
};

export type Mission = ResourceHeader & {
  kind: "mission";
  mission_revision: Revision;
  run_generations: {
  [key: string]: Id;
};
  runs: Array<Id>;
  state: "draft" | "ready" | "running" | "standing" | "completed" | "failed" | "cancelled";
  title: string;
  usage?: (UsageSummary | null);
  visualization?: Visualization;
};

export type Operation = ResourceHeader & {
  component: "daemon" | "host" | "transport" | "observer" | "runtime" | "action";
  kind: "operation";
  severity: "critical" | "warning" | "info";
  state: "pending" | "running" | "healthy" | "degraded" | "failed" | "completed";
  summary: string;
  targets?: Array<Id>;
};

export type Page = {
  collection: string;
  filters: {
  [key: string]: string;
};
  items: Array<Resource>;
  kind: "page";
  page: PageInfo;
};

export type PageInfo = {
  cursor_expires_at?: (Timestamp | null);
  has_more: boolean;
  limit: number;
  next_cursor?: string | null;
};

export type PairedSession = {
  credential: string;
  device_id: Id;
  expires_at: Timestamp;
  kind: "paired-session";
  person_id: string;
  scopes: Array<string>;
  session_actor: Id;
};

export type PairingBegin = {
  api_version: "st3.client.v0";
  device_name: string;
  person_id: string;
};

export type PairingChallenge = {
  code: string;
  expires_at: Timestamp;
  kind: "pairing-challenge";
  pairing_id: Id;
};

export type PairingComplete = {
  api_version: "st3.client.v0";
  code: string;
  device_public_key: string;
};

export type PlannerConfig = {
  effort?: string;
  model?: string;
  provider: "codex" | "claude" | "pi" | "omp" | "opencode";
};

export type ProjectionEvent = Omit<{
  body: {

};
  epoch: string;
  id: Id;
  next_cursor: Cursor;
  previous_cursor: Cursor;
  resource_ids: Array<Id>;
  sequence: number;
  snapshot_id: Id;
  timestamp: Timestamp;
  type: "upsert" | "delete" | "timeline.delta" | "terminal.available" | "capabilities.changed";
}, 'type' | 'body'> & ({ type: "timeline.delta"; body: TimelineDelta });

export type Resource = (Attention | Message | Launch | LaunchVariant | LaunchDecision | LaunchApproval | Mission | Work | Agent | Runtime | Machine | Device | Operation | History | Session);

export type ResourceHeader = {
  id: Id;
  kind: "attention" | "message" | "launch" | "launch-variant" | "launch-decision" | "launch-approval" | "mission" | "work" | "agent" | "runtime" | "device" | "operation" | "history" | "session";
  revision: Revision;
  updated_at: Timestamp;
};

export type Revision = string;

export type Runtime = ResourceHeader & {
  desired_revision: Revision;
  incarnation_id: string | null;
  kind: "runtime";
  owner_host_id: Id;
  owner_id: Id;
  owner_run_id?: (Id | null);
  runtime_id: string;
  runtime_kind: "agent" | "exec" | "terminal" | "observer" | "gate";
  state: "pending" | "starting" | "running" | "stopping" | "stopped" | "exited" | "failed" | "unreachable";
  terminal_access?: {

} | null;
  terminal_id?: (Id | null);
  terminal_sequence?: number | null;
};

export type Session = ResourceHeader & {
  ended_at?: (Timestamp | null);
  kind: "session";
  owner_id: Id;
  started_at: Timestamp;
  state: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled";
  timeline_cursor: Cursor;
  usage?: (UsageSummary | null);
};

export type Snapshot = {
  created_at: Timestamp;
  host_id: Id;
  id: Id;
  projection_version: "client-projection.v0";
  store_index: number;
};

export type StructuredDiff = {
  changes: Array<{

}>;
  predicted_actions: Array<{

}>;
};

export type TargetParameters = {
  evidence?: Array<Id>;
  reason?: string;
  summary?: string;
  target_id: Id;
};

export type TerminalAttachment = {
  attachment_id: Id;
  expires_at: Timestamp;
  owner_host_id: Id;
  runtime_incarnation: string;
  state: "available" | "consumed" | "detached" | "expired";
  stream_capability: string | null;
  stream_url: string;
  terminal_id: Id;
};

export type TerminalExitBody = {
  exit_code?: number | null;
  exit_signal?: number | null;
  reason?: string;
};

export type TerminalFrame = Omit<{
  body: {

};
  id: Id;
  runtime_incarnation: string;
  sequence: number;
  terminal_id: Id;
  timestamp: Timestamp;
  type: "output" | "resize" | "title" | "bell" | "exit" | "resync";
}, 'type' | 'body'> & ({ type: "output"; body: TerminalOutputBody } | { type: "resize"; body: TerminalResizeBody } | { type: "title"; body: {
  title: string;
} } | { type: "bell"; body: {

} } | { type: "exit"; body: TerminalExitBody } | { type: "resync"; body: {
  screen: TerminalScreen;
} });

export type TerminalFramePage = {
  frames: Array<TerminalFrame>;
  kind: "terminal-frame-page";
  resume_sequence: number;
  runtime_incarnation: string;
  terminal_id: Id;
};

export type TerminalLine = {
  redacted: boolean;
  row: number;
  text: string;
  truncated: boolean;
};

export type TerminalOutputBody = {
  data_base64: string;
  redacted: boolean;
  truncated: boolean;
};

export type TerminalResizeBody = {
  columns: number;
  rows: number;
};

export type TerminalScreen = {
  columns: number;
  cursor: {
  column: number;
  row: number;
  visible: boolean;
};
  kind: "terminal-screen";
  lines: Array<TerminalLine>;
  next_sequence: number;
  rows: number;
  runtime_incarnation: string;
  terminal_id: Id;
  title: string;
  truncated: boolean;
};

export type TimelineContentBody = (unknown | unknown);

export type TimelineDelta = {
  entry?: TimelineEntry;
  entry_id: Id;
  operation: "append" | "replace" | "finalize";
  revision: number;
};

export type TimelineEntry = Omit<{
  body: {

};
  final: boolean;
  id: Id;
  revision: number;
  role: "system" | "user" | "assistant" | "tool";
  sequence: number;
  timestamp: Timestamp;
  type: "message" | "content" | "tool_call" | "tool_result" | "status" | "error" | "usage" | "redaction" | "truncation";
}, 'type' | 'body'> & ({ type: "message"; body: TimelineMessageBody } | { type: "content"; body: TimelineContentBody } | { type: "tool_call"; body: TimelineToolCallBody } | { type: "tool_result"; body: TimelineToolResultBody } | { type: "status"; body: TimelineStatusBody } | { type: "error"; body: TimelineErrorBody } | { type: "usage"; body: TimelineUsageBody } | { type: "redaction"; body: TimelineRedactionBody } | { type: "truncation"; body: TimelineTruncationBody });

export type TimelineErrorBody = {
  code: string;
  details: {

};
  message: string;
  retryable: boolean;
};

export type TimelineMessageBody = {
  message_id: string;
  reply_to?: string;
};

export type TimelinePage = {
  items: Array<TimelineEntry>;
  kind: "timeline-page";
  page: PageInfo;
  session_id: Id;
};

export type TimelineRedactionBody = {
  reason: string;
  withheld_bytes: number;
  withheld_items?: number;
};

export type TimelineStatusBody = {
  detail?: string;
  status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled";
};

export type TimelineToolCallBody = {
  arguments: unknown;
  call_id: string;
  name: string;
};

export type TimelineToolResultBody = {
  call_id: string;
  content: unknown;
  media_type: string;
  status: "success" | "error";
};

export type TimelineTruncationBody = {
  continuation_cursor?: Cursor;
  omitted_from_sequence: number;
  omitted_to_sequence: number;
  reason: string;
};

export type TimelineUsageBody = {
  attribution: {
  agent_id: Id;
  generation_id?: string | null;
  mission_run_id?: string | null;
  step_id?: string | null;
};
  cached_tokens?: number;
  compactions?: number;
  context_used_percent?: number;
  context_used_tokens?: number;
  context_window_tokens?: number;
  cost?: number;
  currency?: string;
  driver: string;
  input_tokens?: number;
  last_compaction_ms?: number;
  last_compaction_trigger?: "manual" | "auto" | "threshold" | "overflow" | "idle" | "unknown";
  model?: string;
  output_tokens?: number;
  semantics: "context_occupancy" | "session_cumulative" | "response";
  total_tokens?: number;
};

export type Timestamp = string;

export type UsageContext = {
  compactions?: number;
  last_compaction_ms?: number;
  last_compaction_trigger?: "manual" | "auto" | "threshold" | "overflow" | "idle" | "unknown";
  model?: string;
  observed_at_unix_ms: number;
  used_percent?: number;
  used_tokens?: number;
  window_tokens?: number;
};

export type UsageSummary = {
  aggregation: "cumulative-per-incarnation-else-response-deltas";
  cached_tokens: number;
  context?: UsageContext;
  cost?: number;
  currency?: string;
  incarnation_count: number;
  input_tokens: number;
  output_tokens: number;
  total_tokens: number;
};

export type Visualization = {
  constraints: Array<string>;
  decisions: Array<LaunchDecision>;
  diffs: Array<StructuredDiff>;
  edges: Array<VisualizationEdge>;
  gates: Array<{

}>;
  goals: Array<string>;
  groups: Array<VisualizationGroup>;
  live_progress: {

};
  mission?: string;
  nodes: Array<VisualizationNode>;
  resources: Array<{

}>;
  revision: {

};
  risk: {

};
  swimlanes: Array<{
  assignment: string;
  id: string;
  nodes: Array<string>;
}>;
  timeline: {
  entries: Array<{

}>;
};
  version: "st3.visualization.v0";
  views: Array<"graph" | "timeline" | "swimlane" | "revision" | "risk" | "live-progress">;
};

export type VisualizationEdge = {
  from: string | null;
  gate: unknown;
  id: string;
  kind: "dependency" | "gate";
  to: string;
};

export type VisualizationGroup = {
  id: string;
  kind: "queue" | "nested-mission";
  members: Array<string>;
};

export type VisualizationNode = {
  assignment?: unknown;
  constraints: Array<string>;
  gates?: Array<unknown>;
  goals: Array<string>;
  id: string;
  kind: string;
  label: string;
  loop?: unknown;
  path: string;
  resources?: Array<unknown>;
  retry?: {

};
  runtime: {

};
  source_references?: Array<unknown>;
  timeout_ms?: number | null;
};

export type Work = ResourceHeader & {
  attempt: number;
  blocked_reason?: string | null;
  blockers?: Array<Id>;
  claim_incarnation?: string | null;
  claimant?: (Id | null);
  constraints: Array<string>;
  definition_id: Revision;
  generation_id: Id;
  goals: Array<string>;
  kind: "work";
  mission_run_id: Id;
  path: string;
  readiness_epoch: number;
  state: "waiting" | "ready" | "claimed" | "blocked" | "verifying" | "completed" | "failed" | "cancelled";
  usage?: (UsageSummary | null);
};

export type ActionRequest =
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'attention.resolve'; parameters: {
  attention_id: Id;
  outcome: string;
  reason?: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.approve'; parameters: {
  launch_id: Id;
  variant_id: Id;
}; fence: Fence & Required<Pick<Fence, 'preview_token'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.cancel'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.create'; parameters: {
  effort?: string;
  model?: string;
  provider?: "codex" | "claude" | "pi" | "omp" | "opencode";
  request: string;
  target: ({
  mission_id: Id;
  type: "new-mission";
  workspace: string;
} | {
  generation_id: Id;
  mission_run_id: Id;
  type: "mission-run";
});
  title: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.preview'; parameters: {
  launch_id: Id;
  variant_id: Id;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'launch.revise'; parameters: {
  feedback: string;
  launch_id: Id;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'message.close'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'message.read'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'message.send'; parameters: {
  content: string;
  in_reply_to?: Id;
  session_id?: Id;
  tags?: Array<string>;
  title?: string;
  to: Id;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.approve-revision'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'preview_token' | 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.cancel'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.cancel-revision'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.revise'; parameters: {
  launch_id: Id;
  mission_run_id: Id;
}; fence: Fence & Required<Pick<Fence, 'mission_generation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'mission.start'; parameters: {
  inputs: {
  [key: string]: string;
};
  mission_id: Id;
  workspace: string;
}; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'pairing.revoke'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'review.approve'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'review.reject'; parameters: TargetParameters; fence: Fence }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.context-clear'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.reset'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.restart'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.signal'; parameters: {
  signal: "interrupt" | "terminate" | "kill";
  target_id: Id;
}; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'runtime.stop'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'session.import'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'subject_revisions'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.attach'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'terminal_sequence'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.detach'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'terminal_sequence'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.input'; parameters: {
  mode: "line" | "raw" | "key";
  terminal_id: Id;
  value: string;
}; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'terminal_sequence'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'terminal.resize'; parameters: {
  columns: number;
  rows: number;
  terminal_id: Id;
}; fence: Fence & Required<Pick<Fence, 'runtime_incarnation' | 'terminal_sequence'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.claim'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.complete'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.fail'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.progress'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.publish-mission'; parameters: {
  mission: {

};
  name: string;
  target_id: Id;
}; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch' | 'runtime_incarnation'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.release'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> }) |
  (Omit<ActionCommon, 'type' | 'parameters' | 'fence'> & { type: 'work.renew'; parameters: TargetParameters; fence: Fence & Required<Pick<Fence, 'mission_generation' | 'step_definition' | 'attempt' | 'readiness_epoch'>> });
export type ActionOf<T extends ActionRequest['type']> = Extract<ActionRequest, { type: T }>;
export type EnvelopeOf<T> = Omit<Envelope, 'value'> & { value: T };
